"""Claim revisions carried in the capsule (2040 slice 5, P5.3).

``collect_claim_revisions`` writes ``records/claim_revisions.json`` from the
sealed store without writing the store; ``claim_chain_verify`` (stdlib only)
re-verifies it and must agree with aihydro-core on shared golden vectors
(``tests/data/claim_chain_vectors.json``, regenerated by
``tests/data/gen_claim_chain_vectors.py``). All content is synthetic.
"""
from __future__ import annotations

import ast
import json
import re
import sqlite3
from pathlib import Path

import pytest

from aihydro_core.export.rocrate import PATH_PATTERN
from aihydro_core.records import ClaimRevision, digest, verify_chain, verify_claim_revision_dict

from ai_hydro.capsule import claim_chain_verify as ccv
from ai_hydro.capsule.claim_records import collect_claim_revisions
from ai_hydro.mcp.tools_ledger import add_claim, update_claim_status
from ai_hydro.session import claim_revisions as cr
from ai_hydro.session import store
from ai_hydro.session.store import HydroSession
from approval_helpers import basin_ref_full
from test_approval import _run_record

VECTORS = Path(__file__).parent / "data" / "claim_chain_vectors.json"
_ABS = PATH_PATTERN       # core's shared local-path leak pattern


@pytest.fixture(autouse=True)
def isolated(tmp_path, monkeypatch):
    monkeypatch.setattr(store, "_SESSIONS_DIR", tmp_path / "sessions")
    monkeypatch.setattr(store, "_REPO_ROOT", tmp_path)


@pytest.fixture
def session():
    s = HydroSession("rev")
    s.set("_run_log", {"r1": _run_record("rev")})
    s.save()
    return s


def _add(claim_id="c1", **over):
    args = dict(session_id="rev", claim_id=claim_id, statement="Synthetic NSE is 0.8",
                claim_type="empirical_result", status="proposed", confidence="low",
                confidence_rationale="Synthetic regression fixture only.",
                basins=["synthetic"], period="2000-2001", metric="nse",
                basin_refs=[basin_ref_full("synthetic")],
                limitations=["Synthetic regression case, no real research conclusion."],
                evidence_spans=[{"source_type": "run", "source_id": "r1", "metric_ref": "nse"}])
    args.update(over)
    assert add_claim(**args)["status"] == "recorded"


def _supported(claim_id="c1"):
    update_claim_status("rev", claim_id, "supported", "medium",
                        "Synthetic regression fixture only.", uncertainty_verified=True)


def _raw():
    conn = cr._connect("rev", create=False)
    conn.execute("DROP TRIGGER IF EXISTS claim_revisions_no_update")
    conn.execute("DROP TRIGGER IF EXISTS claim_revisions_no_delete")
    return conn


def _doc(cap: Path) -> dict:
    return json.loads((cap / "records" / "claim_revisions.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------- round trip
def test_real_store_round_trip_verifies_in_stdlib(session, tmp_path):
    _add(); _supported(); _add("c2")
    cap = tmp_path / "cap"
    entries, counts = collect_claim_revisions("rev", cap, tmp_path)
    assert [e["claim_id"] for e in entries] == ["c1", "c2"]
    assert counts == {"claims": 2, "ok": 2, "corrupt": 0, "revisions": counts["revisions"],
                      "redacted": 0, "source": counts["source"]}
    assert counts["revisions"] >= 3
    doc = _doc(cap)
    store_rows = cr.history("rev")
    for cid in ("c1", "c2"):                        # verbatim: sealed rows unchanged
        assert doc["claims"][cid]["rows"] == store_rows[cid]["rows"]
        assert verify_chain([ClaimRevision.from_dict(r) for r in doc["claims"][cid]["rows"]])
    heads = {e["claim_id"]: e["head_revision_digest"] for e in entries}
    verdicts = ccv.verify_exported(doc, heads)
    assert {c: v["status"] for c, v in verdicts.items()} == {"c1": "verified", "c2": "verified"}


def test_output_is_deterministic(session, tmp_path):
    _add(); _supported()
    collect_claim_revisions("rev", tmp_path / "a", tmp_path)
    collect_claim_revisions("rev", tmp_path / "b", tmp_path)
    assert (tmp_path / "a/records/claim_revisions.json").read_bytes() == \
           (tmp_path / "b/records/claim_revisions.json").read_bytes()


def test_absent_store_writes_nothing(session, tmp_path):
    cap = tmp_path / "cap"
    entries, counts = collect_claim_revisions("rev", cap, tmp_path)
    assert entries == [] and counts["source"] == "absent" and counts["claims"] == 0
    assert not (cap / "records").exists()


def test_collect_never_writes_the_store(session, tmp_path):
    _add()
    db = Path(store._SESSIONS_DIR) / "rev.claims.sqlite3"
    before, mtime = db.read_bytes(), db.stat().st_mtime_ns
    names = {p.name for p in db.parent.iterdir()}
    collect_claim_revisions("rev", tmp_path / "cap", tmp_path)
    assert db.read_bytes() == before and db.stat().st_mtime_ns == mtime
    # SQLite may create -wal/-shm sidecars to read a WAL store; nothing else appears
    assert {p.name for p in db.parent.iterdir()} - names <= {db.name + "-wal", db.name + "-shm"}


# ---------------------------------------------------------------- tamper
def test_edited_row_marks_only_that_claim_corrupt(session, tmp_path):
    _add(); _add("c2")
    conn = _raw()
    conn.execute("UPDATE claim_revisions SET row_json = replace(row_json, 'proposed', 'supported')"
                 " WHERE claim_id = 'c1'")
    conn.close()
    cap = tmp_path / "cap"
    entries, counts = collect_claim_revisions("rev", cap, tmp_path)
    by = {e["claim_id"]: e for e in entries}
    assert by["c1"]["status"] == "corrupt" and by["c1"]["revisions"] == 0 and by["c1"]["error"]
    assert by["c2"]["status"] == "ok"
    assert counts["corrupt"] == 1 and counts["ok"] == 1
    doc = _doc(cap)
    assert "rows" not in doc["claims"]["c1"]                 # fail closed: no rows from a bad chain
    verdicts = ccv.verify_exported(doc)
    assert verdicts["c1"]["status"] == "corrupt_at_export" and verdicts["c2"]["status"] == "verified"


def test_dropped_middle_revision_is_corrupt_in_the_store(session, tmp_path):
    _add(); _supported(); update_claim_status("rev", "c1", "supported", "high",
                                              "Synthetic regression fixture only.", uncertainty_verified=True)
    assert len(cr.history("rev")["c1"]["rows"]) >= 3
    conn = _raw()
    conn.execute("DELETE FROM claim_revisions WHERE claim_id='c1' AND revision = 1")
    conn.close()
    entries, _ = collect_claim_revisions("rev", tmp_path / "cap", tmp_path)
    assert entries[0]["status"] == "corrupt"


def test_dropped_revision_in_exported_file_fails_verification(session, tmp_path):
    _add(); _supported()
    update_claim_status("rev", "c1", "supported", "high", "Synthetic regression fixture only.",
                        uncertainty_verified=True)
    cap = tmp_path / "cap"
    entries, _ = collect_claim_revisions("rev", cap, tmp_path)
    doc = _doc(cap)
    rows = doc["claims"]["c1"]["rows"]
    assert len(rows) >= 3
    doc["claims"]["c1"]["rows"] = [rows[0], *rows[2:]]       # middle dropped after export
    assert ccv.verify_exported(doc)["c1"]["status"] == "failed"


def test_truncated_chain_needs_an_anchor(session, tmp_path):
    """A cut tail still chains; only an external head anchor exposes it (documented limit)."""
    _add(); _supported()
    cap = tmp_path / "cap"
    entries, _ = collect_claim_revisions("rev", cap, tmp_path)
    head = entries[0]["head_revision_digest"]
    doc = _doc(cap)
    doc["claims"]["c1"]["rows"] = doc["claims"]["c1"]["rows"][:-1]
    assert ccv.verify_exported(doc)["c1"]["status"] == "verified"          # chain alone cannot tell
    assert ccv.verify_exported(doc, {"c1": head})["c1"]["status"] == "failed"
    # the same truncation made in the store itself is likewise invisible to the chain
    conn = _raw()
    conn.execute("DELETE FROM claim_revisions WHERE claim_id='c1' AND revision >= 1")
    conn.close()
    entries2, _ = collect_claim_revisions("rev", tmp_path / "cap2", tmp_path)
    assert entries2[0]["status"] == "ok" and entries2[0]["head_revision_digest"] != head


def test_edited_exported_row_fails_verification(session, tmp_path):
    _add(); _supported()
    cap = tmp_path / "cap"
    collect_claim_revisions("rev", cap, tmp_path)
    doc = _doc(cap)
    doc["claims"]["c1"]["rows"][-1]["content"]["status"] = "contested"
    assert ccv.verify_exported(doc)["c1"]["status"] == "failed"


# ---------------------------------------------------------------- privacy
def _insert_path_row(path_text):
    rows = cr.history("rev")["c1"]["rows"]
    prev = ClaimRevision.from_dict(rows[-1])
    content = {**prev.content, "note": f"data read from {path_text}"}
    new = ClaimRevision(session_id="rev", claim_id="c1", revision=prev.revision + 1,
                        supersedes=prev.revision_digest, revision_digest=digest(content),
                        content=content, cause={"tool": "update_claim_status", "reason": "redefined"},
                        actor=prev.actor).seal()
    conn = cr._connect("rev", create=False)
    cr._insert_sealed(conn, new)
    conn.close()
    return new


def test_path_bearing_row_becomes_a_redacted_stub(session, tmp_path):
    _add(); _supported()
    secret = "/Users/zz-someone/private-data/x.csv"
    bad = _insert_path_row(secret)
    assert cr.history("rev")["c1"]["ok"]                      # sealed, valid in the store
    cap = tmp_path / "cap"
    entries, counts = collect_claim_revisions("rev", cap, tmp_path)
    assert counts["redacted"] == 1 and entries[0]["redacted_revisions"] == [bad.revision]
    text = (cap / "records/claim_revisions.json").read_text(encoding="utf-8")
    assert "zz-someone" not in text and "private-data" not in text
    stub = _doc(cap)["claims"]["c1"]["rows"][-1]
    assert stub["redacted_for_privacy"] is True
    assert stub["revision_digest"] == bad.revision_digest and stub["record_digest"] == bad.record_digest
    assert stub["supersedes"] == bad.supersedes and "content" not in stub
    v = ccv.verify_exported(_doc(cap), {"c1": bad.revision_digest})["c1"]
    assert v["status"] == "partial"
    # stubs hide nothing: an edit to a neighbouring verbatim row still fails
    doc = _doc(cap)
    doc["claims"]["c1"]["rows"][0]["content"]["status"] = "contested"
    assert ccv.verify_exported(doc)["c1"]["status"] == "failed"


def test_stub_with_broken_link_fails(session, tmp_path):
    _add(); _supported()
    _insert_path_row("/Users/zz-someone/private-data/x.csv")
    cap = tmp_path / "cap"
    collect_claim_revisions("rev", cap, tmp_path)
    doc = _doc(cap)
    doc["claims"]["c1"]["rows"][-1]["supersedes"] = "sha256:" + "0" * 64
    assert ccv.verify_exported(doc)["c1"]["status"] == "failed"


def test_output_is_path_free(session, tmp_path):
    _add(); _supported(); _add("c2")
    _insert_path_row("/Users/zz-someone/private-data/x.csv")
    conn = _raw()                                             # a corrupt claim whose error could echo a path
    conn.execute("UPDATE claim_revisions SET row_json = replace(row_json, 'proposed', 'x')"
                 " WHERE claim_id = 'c2'")
    conn.close()
    cap = tmp_path / "cap"
    entries, _ = collect_claim_revisions("rev", cap, tmp_path)
    blob = (cap / "records/claim_revisions.json").read_text(encoding="utf-8") + json.dumps(entries)
    assert not _ABS.search(blob), _ABS.search(blob)
    assert str(tmp_path) not in blob


# ---------------------------------------------------------------- stdlib verifier vs core
def _vectors():
    return json.loads(VECTORS.read_text(encoding="utf-8"))["vectors"]


@pytest.mark.parametrize("vec", _vectors(), ids=lambda v: v["name"])
def test_stdlib_verifier_agrees_with_core_on_goldens(vec):
    rows = vec["rows"]
    # the golden file is core's verdict, and core still gives it (stale-vector guard)
    assert [verify_claim_revision_dict(r) for r in rows] == vec["row_ok"]
    try:
        core_chain = bool(rows) and verify_chain([ClaimRevision.from_dict(r) for r in rows])
    except Exception:
        core_chain = False
    assert core_chain == vec["chain_ok"]
    assert [ccv.verify_claim_revision(r) for r in rows] == vec["row_ok"]
    assert ccv.verify_chain(rows) == vec["chain_ok"]


def test_vectors_cover_pass_and_fail_cases():
    names = {v["name"] for v in _vectors()}
    assert {"valid_chain", "content_edited", "middle_dropped", "unknown_fields_roundtrip",
            "numeric_edge_content"} <= names
    assert any(v["chain_ok"] for v in _vectors()) and any(not v["chain_ok"] for v in _vectors())


def test_stdlib_verifier_agrees_with_core_on_real_rows(session):
    _add(); _supported()
    rows = cr.history("rev")["c1"]["rows"]
    assert ccv.verify_chain(rows) and all(ccv.verify_claim_revision(r) for r in rows)


def test_verifier_module_is_stdlib_only():
    tree = ast.parse(Path(ccv.__file__).read_text(encoding="utf-8"))
    mods = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            mods |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            mods.add((node.module or "").split(".")[0])
    assert mods <= {"__future__", "decimal", "hashlib", "math"}, mods
