"""Signed approvals (ADR-002b): SSHSIG over the record digest, verifier-derived channel.

Uses throwaway software ed25519 keys generated by ``ssh-keygen`` inside a
scratch ``HOME`` (``tmp_path``); nothing touches ``~/.ssh`` or ``~/.aihydro``.
Hardware (``sk-``) keys cannot be exercised without a device: the channel
derivation for them is covered with a stubbed ``ssh-keygen -Y verify``.
"""
from __future__ import annotations

import base64
import json
import os
import select
import shutil
import struct
import subprocess
import sys
import time
from pathlib import Path

import pytest
from aihydro_core.records import Actor

from ai_hydro.approval import records, trust
from ai_hydro.approval.cli import main as approve_cli
from ai_hydro.approval.records import find_approval, approval_stamp, verified_channel
from ai_hydro.approval.signing import enrol_line, read_pubkey_file, sign_digest, resolve_key
from ai_hydro.approval.writer import write_approval, write_signed_approval
from ai_hydro.session import store
from ai_hydro.session.store import HydroSession

REPO = Path(__file__).resolve().parent.parent
REV = "sha256:" + "ab" * 32
HUMAN = Actor(kind="human", id="alice")

pytestmark = pytest.mark.skipif(shutil.which("ssh-keygen") is None, reason="needs OpenSSH ssh-keygen")


@pytest.fixture(autouse=True)
def scratch_home(tmp_path, monkeypatch):
    """Scratch HOME; no system trust root; no agent; no inherited policy overrides."""
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("AIHYDRO_SYSTEM_TRUST_FILE", str(tmp_path / "etc" / "allowed_signers"))
    monkeypatch.delenv("SSH_AUTH_SOCK", raising=False)
    monkeypatch.delenv("AIHYDRO_REQUIRE_SIGNED", raising=False)
    return tmp_path


@pytest.fixture
def opt_out(monkeypatch):
    monkeypatch.setenv("AIHYDRO_REQUIRE_SIGNED", "0")


def make_key(directory: Path, name: str = "k") -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / name
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", name, "-f", str(path)],
                   check=True, capture_output=True)
    return path


def enrol(key: Path, *, user=True, **kw) -> str:
    line = enrol_line(read_pubkey_file(Path(str(key) + ".pub")), "alice", kw.get("after"), kw.get("before"))
    if user:
        path = trust.user_trust_file()
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "a") as fh:
            fh.write(line + "\n")
    return line


def approvals_lines():
    f = records.approvals_file()
    return [json.loads(x) for x in f.read_text().splitlines()] if f.exists() else []


def sign_manually(rec_body: dict, key: Path, tmp_path: Path) -> dict:
    """What an attacker holding `key` (enrolled or not) can do: seal + sign a v2 record by hand."""
    pub = read_pubkey_file(Path(str(key) + ".pub"))
    rec = records.seal_record({**rec_body, "schema": records.APPROVAL_SCHEMA_V2,
                               "signer": {"fingerprint": pub["fingerprint"], "key_type": pub["key_type"]}})
    armored = sign_digest(rec["record_digest"], {"pub": pub, "path": key, "agent": False}, tmp_path)
    rec["signature"] = {"format": "sshsig", "namespace": trust.NAMESPACE, "armored": armored}
    return rec


BODY = {"claim_id": "c1", "session_id": "s1", "claim_revision_digest": REV,
        "approver": {"kind": "human", "id": "alice"}, "approved_at": "2026-01-01T00:00:00Z",
        "statement": "x"}


def put(rec: dict):
    records.approvals_dir().mkdir(parents=True, exist_ok=True)
    with open(records.approvals_file(), "a") as fh:
        fh.write(json.dumps(rec) + "\n")


# --------------------------------------------------------------------------- roundtrip

def test_sign_and_verify_roundtrip(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    assert rec["schema"] == "aihydro.approval/2" and "channel" not in rec
    assert rec["signature"]["namespace"] == "aihydro-approval@v1"
    fp = subprocess.run(["ssh-keygen", "-lf", f"{key}.pub"], capture_output=True, text=True).stdout.split()[1]
    assert rec["signer"] == {"fingerprint": fp, "key_type": "ssh-ed25519"}
    found = find_approval("s1", "c1", REV)
    assert found["record_digest"] == rec["record_digest"]
    assert verified_channel(found) == "ssh_sig_user_trust"
    stamp = approval_stamp(found)
    assert stamp == {"record_digest": rec["record_digest"], "channel": "ssh_sig_user_trust",
                     "signer": rec["signer"], "trust_root": "user_writable",
                     "principal": "alice", "policy": "signed_required"}


def _system_trust(scratch_home, key, monkeypatch, protected=True):
    """Install a system-path trust file. ``protected`` simulates root ownership (we cannot chown)."""
    sysfile = Path(os.environ["AIHYDRO_SYSTEM_TRUST_FILE"])
    sysfile.parent.mkdir(parents=True)
    sysfile.write_text(enrol(key, user=False) + "\n")
    if protected:
        os.chmod(sysfile, 0o444)
        os.chmod(sysfile.parent, 0o555)
        real = os.geteuid()
        monkeypatch.setattr(trust.os, "geteuid", lambda: real + 1)   # file is "owned by someone else"
    return sysfile


@pytest.mark.skipif(os.name != "posix" or (hasattr(os, "geteuid") and os.geteuid() == 0),
                    reason="needs a non-root POSIX user (root can always write)")
def test_protected_system_trust_root_earns_system_label(scratch_home, monkeypatch):
    key = make_key(scratch_home / "keys")
    sysfile = _system_trust(scratch_home, key, monkeypatch)
    try:
        assert trust.trust_root() == (sysfile, "system")
        rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
        stamp = approval_stamp(rec)
        assert stamp["trust_root"] == "system" and stamp["channel"] == "ssh_sig_system_trust"
    finally:
        os.chmod(sysfile.parent, 0o755)


def test_system_path_file_writable_or_owned_by_user_is_user_writable(scratch_home, monkeypatch):
    """G5: the /etc path alone does not earn 'system'."""
    key = make_key(scratch_home / "keys")
    sysfile = _system_trust(scratch_home, key, monkeypatch, protected=False)   # we own it and can write it
    assert trust.trust_root() == (sysfile, "user_writable")
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    assert approval_stamp(rec)["trust_root"] == "user_writable"
    assert approval_stamp(rec)["channel"] == "ssh_sig_user_trust"


@pytest.mark.skipif(os.name != "posix" or (hasattr(os, "geteuid") and os.geteuid() == 0),
                    reason="needs a non-root POSIX user")
def test_unwritable_but_user_owned_system_file_is_not_system(scratch_home, monkeypatch):
    key = make_key(scratch_home / "keys")
    sysfile = _system_trust(scratch_home, key, monkeypatch, protected=False)
    os.chmod(sysfile, 0o444)
    os.chmod(sysfile.parent, 0o555)           # not writable, but we own both: we could chmod them back
    try:
        assert trust.trust_root()[1] == "user_writable"
    finally:
        os.chmod(sysfile.parent, 0o755)


@pytest.mark.skipif(os.name != "posix" or (hasattr(os, "geteuid") and os.geteuid() == 0),
                    reason="needs a non-root POSIX user")
def test_writable_directory_blocks_system_label(scratch_home, monkeypatch):
    key = make_key(scratch_home / "keys")
    sysfile = _system_trust(scratch_home, key, monkeypatch)
    try:
        os.chmod(sysfile.parent, 0o755)       # file read-only and "foreign", but directory writable
        assert trust.trust_root()[1] == "user_writable"
    finally:
        os.chmod(sysfile.parent, 0o755)


def test_approver_must_match_enrolled_principal(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)                                                    # principal "alice"
    with pytest.raises(ValueError, match="does not match the enrolled principal"):
        write_signed_approval("s1", "c1", REV, Actor(kind="human", id="bob"), "ok", key=str(key))
    assert approvals_lines() == []
    put(sign_manually({**BODY, "approver": {"kind": "human", "id": "bob"}}, key, scratch_home))
    assert find_approval("s1", "c1", REV) is None


def test_default_key_from_ssh_dir_is_used(scratch_home):
    key = make_key(scratch_home / ".ssh", "id_ed25519")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok")
    assert find_approval("s1", "c1", REV)["record_digest"] == rec["record_digest"]


def test_supplied_allowed_signers_verifies_off_machine(scratch_home):
    """The replay path: verify against a file the verifier brings, not the local trust root."""
    key = make_key(scratch_home / "keys")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    other = scratch_home / "published_keys"
    other.write_text(enrol(key, user=False) + "\n")
    shutil.rmtree(trust.user_trust_file().parent)            # no local trust root at all
    assert trust.check_approval(rec).ok is False
    v = trust.check_approval(rec, allowed_signers=other)
    assert v.ok and v.trust_root == "supplied" and v.channel == "ssh_sig_supplied"
    stranger = make_key(scratch_home / "keys2")
    other.write_text(enrol(stranger, user=False) + "\n")
    assert not trust.check_approval(rec, allowed_signers=other).ok


# --------------------------------------------------------------------------- refusals

def test_sealed_v2_line_without_signature_is_refused(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)
    pub = read_pubkey_file(Path(f"{key}.pub"))
    signer = {"fingerprint": pub["fingerprint"], "key_type": pub["key_type"]}
    put(records.seal_record({**BODY, "schema": records.APPROVAL_SCHEMA_V2, "signer": signer}))
    assert find_approval("s1", "c1", REV) is None


@pytest.mark.parametrize("sig", [
    {"format": "sshsig", "namespace": "aihydro-approval@v1", "armored": "garbage"},
    {"format": "sshsig", "namespace": "aihydro-approval@v1",
     "armored": "-----BEGIN SSH SIGNATURE-----\nAAAA\n-----END SSH SIGNATURE-----"},
    {"format": "gpg", "namespace": "aihydro-approval@v1", "armored": "x"},
    "not-a-dict",
])
def test_sealed_v2_line_with_invalid_signature_is_refused(scratch_home, sig):
    key = make_key(scratch_home / "keys")
    enrol(key)
    pub = read_pubkey_file(Path(f"{key}.pub"))
    rec = records.seal_record({**BODY, "schema": records.APPROVAL_SCHEMA_V2,
                               "signer": {"fingerprint": pub["fingerprint"], "key_type": pub["key_type"]}})
    put({**rec, "signature": sig})
    assert find_approval("s1", "c1", REV) is None


def test_signature_replayed_from_another_record_is_refused(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)
    genuine = write_signed_approval("s1", "c-other", REV, HUMAN, "ok", key=str(key))
    forged = records.seal_record({**BODY, "schema": records.APPROVAL_SCHEMA_V2, "signer": genuine["signer"]})
    put({**forged, "signature": genuine["signature"]})    # valid signature, over a different digest
    assert find_approval("s1", "c1", REV) is None
    assert find_approval("s1", "c-other", REV) is not None


def test_edited_v2_body_fails_the_seal(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    lines = approvals_lines()
    lines[-1]["statement"] = "edited"
    records.approvals_file().write_text("".join(json.dumps(x) + "\n" for x in lines))
    assert find_approval("s1", "c1", REV) is None
    assert rec["record_digest"]


def test_signer_field_must_match_signing_key(scratch_home):
    key = make_key(scratch_home / "keys")
    other = make_key(scratch_home / "keys", "other")
    enrol(key)
    pub = read_pubkey_file(Path(f"{other}.pub"))
    body = {**BODY, "schema": records.APPROVAL_SCHEMA_V2,
            "signer": {"fingerprint": read_pubkey_file(Path(f"{key}.pub"))["fingerprint"],
                       "key_type": "ssh-ed25519"}}
    rec = records.seal_record(body)
    rec["signature"] = {"format": "sshsig", "namespace": trust.NAMESPACE,
                        "armored": sign_digest(rec["record_digest"], {"pub": pub, "path": other, "agent": False},
                                               scratch_home)}
    put(rec)                                   # claims the enrolled key, signed by another
    assert find_approval("s1", "c1", REV) is None


def test_unenrolled_key_is_refused(scratch_home):
    enrolled = make_key(scratch_home / "keys", "enrolled")
    rogue = make_key(scratch_home / "keys", "rogue")
    enrol(enrolled)
    with pytest.raises(ValueError, match="not in allowed_signers"):
        write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(rogue))
    assert approvals_lines() == []
    put(sign_manually(BODY, rogue, scratch_home))           # hand-minted with a key the owner never enrolled
    assert find_approval("s1", "c1", REV) is None


def test_expired_and_not_yet_valid_keys_are_refused(scratch_home):
    key = make_key(scratch_home / "keys")
    trust.user_trust_file().parent.mkdir(parents=True)
    trust.user_trust_file().write_text(enrol(key, user=False, before="20200101") + "\n")
    put(sign_manually(BODY, key, scratch_home))
    assert find_approval("s1", "c1", REV) is None
    records.approvals_file().unlink()
    trust.user_trust_file().write_text(enrol(key, user=False, after="20990101") + "\n")
    put(sign_manually(BODY, key, scratch_home))
    assert find_approval("s1", "c1", REV) is None
    records.approvals_file().unlink()
    trust.user_trust_file().write_text(enrol(key, user=False, after="20200101", before="20990101") + "\n")
    put(sign_manually(BODY, key, scratch_home))
    assert find_approval("s1", "c1", REV) is not None      # inside its window


def test_revoked_key_is_refused_including_earlier_approvals(scratch_home):
    key = make_key(scratch_home / "keys")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    assert find_approval("s1", "c1", REV)
    out = _Sink()
    code = approve_cli(["revoke", rec["signer"]["fingerprint"], "--reason", "lost"],
                       stdout=out, stderr=_Sink())
    assert code == 0
    assert "deletable and forgeable" in out.getvalue() and "valid-before" in out.getvalue()
    assert find_approval("s1", "c1", REV) is None
    with pytest.raises(ValueError, match="revoked"):
        write_signed_approval("s1", "c2", REV, HUMAN, "ok", key=str(key))
    lines = [json.loads(x) for x in trust.revocations_file().read_text().splitlines()]
    assert lines[0]["schema"] == "aihydro.approval_revocation/1" and lines[0]["record_digest"].startswith("sha256:")


def test_unsealed_or_edited_revocation_line_is_ignored(scratch_home):
    trust.revocations_file().parent.mkdir(parents=True, exist_ok=True)
    trust.revocations_file().write_text(json.dumps(
        {"schema": trust.REVOCATION_SCHEMA, "fingerprint": "SHA256:x", "record_digest": "sha256:bad"}) + "\n")
    assert trust.revoked_fingerprints() == set()


class _Sink:
    def __init__(self):
        self.buf = []

    def write(self, s):
        self.buf.append(s)

    def flush(self):
        pass

    def isatty(self):
        return False

    def getvalue(self):
        return "".join(self.buf)


# --------------------------------------------------------------------------- legacy v1 policy

def test_fails_closed_by_default_with_no_trust_root(scratch_home):
    """G2: no allowed_signers anywhere and no opt-out: nothing verifies, v1 included."""
    write_approval("s1", "c1", REV, HUMAN, "legacy")
    assert trust.require_signed() is True
    assert find_approval("s1", "c1", REV) is None
    key = make_key(scratch_home / "keys")
    with pytest.raises(ValueError, match="no allowed_signers trust root"):
        write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))


def test_v1_verifies_as_cli_same_user_only_under_explicit_opt_out(scratch_home, opt_out, caplog):
    write_approval("s1", "c1", REV, HUMAN, "legacy")
    assert trust.require_signed() is False
    trust._OPT_OUT_LOGGED = False
    with caplog.at_level("WARNING", logger="ai_hydro.approval"):
        found = find_approval("s1", "c1", REV)
    assert found and verified_channel(found) == "cli_same_user"
    stamp = approval_stamp(found)
    assert stamp["signer"] is None and stamp["policy"] == "unsigned_opt_out"
    assert "opt-out" in caplog.text


def test_signed_record_under_opt_out_is_stamped_with_the_policy(scratch_home, opt_out):
    key = make_key(scratch_home / "keys")
    enrol(key)
    rec = write_signed_approval("s1", "c1", REV, HUMAN, "ok", key=str(key))
    assert approval_stamp(rec)["policy"] == "unsigned_opt_out"


def test_v1_is_refused_once_an_allowed_signers_file_exists_even_under_default(scratch_home):
    key = make_key(scratch_home / "keys")
    write_approval("s1", "c1", REV, HUMAN, "legacy")
    enrol(key)
    assert find_approval("s1", "c1", REV) is None


def test_config_file_opt_out_and_flag_overrides(scratch_home, monkeypatch):
    write_approval("s1", "c1", REV, HUMAN, "legacy")
    assert find_approval("s1", "c1", REV) is None
    cfg = records.approvals_dir() / "config.json"
    cfg.write_text(json.dumps({"require_signed": False}))
    assert find_approval("s1", "c1", REV) is not None
    monkeypatch.setenv("AIHYDRO_REQUIRE_SIGNED", "1")             # env wins over config
    assert find_approval("s1", "c1", REV) is None


@pytest.mark.skipif(os.name != "posix" or (hasattr(os, "geteuid") and os.geteuid() == 0),
                    reason="needs a non-root POSIX user")
def test_protected_system_trust_root_cannot_be_relaxed_by_opt_out(scratch_home, monkeypatch):
    key = make_key(scratch_home / "keys")
    sysfile = _system_trust(scratch_home, key, monkeypatch)
    try:
        write_approval("s1", "c1", REV, HUMAN, "legacy")
        monkeypatch.setenv("AIHYDRO_REQUIRE_SIGNED", "0")
        assert trust.require_signed() is True
        assert find_approval("s1", "c1", REV) is None
    finally:
        os.chmod(sysfile.parent, 0o755)


# --------------------------------------------------------------------------- sk channel (stubbed verify)

def _fake_sshsig(key_type: str) -> tuple:
    blob = struct.pack(">I", len(key_type)) + key_type.encode() + struct.pack(">I", 32) + b"\x07" * 32
    ns = trust.NAMESPACE.encode()
    raw = (b"SSHSIG" + struct.pack(">I", 1) + struct.pack(">I", len(blob)) + blob
           + struct.pack(">I", len(ns)) + ns + struct.pack(">I", 0) + struct.pack(">I", 6) + b"sha512"
           + struct.pack(">I", 0))
    b64 = base64.b64encode(raw).decode()
    armored = "-----BEGIN SSH SIGNATURE-----\n" + b64 + "\n-----END SSH SIGNATURE-----\n"
    return armored, blob


@pytest.mark.parametrize("key_type,options,expect", [
    ("sk-ssh-ed25519@openssh.com", 'namespaces="aihydro-approval@v1"', "ssh_sig_sk_user_trust"),
    ("sk-ecdsa-sha2-nistp256@openssh.com", "", "ssh_sig_sk_user_trust"),
    ("sk-ssh-ed25519@openssh.com", "no-touch-required", "ssh_sig_user_trust"),   # touch not enforced: not claimed
    ("ssh-ed25519", "", "ssh_sig_user_trust"),
])
def test_channel_is_derived_from_key_type_and_touch_policy(scratch_home, monkeypatch, key_type, options, expect):
    armored, blob = _fake_sshsig(key_type)
    fp = trust.key_fingerprint(blob)
    trust.user_trust_file().parent.mkdir(parents=True)
    trust.user_trust_file().write_text(
        f"alice {options + ' ' if options else ''}{key_type} {base64.b64encode(blob).decode()}\n")

    class R:
        def __init__(self, out): self.returncode, self.stdout, self.stderr = 0, out, b""

    def fake_run(args, data=b""):
        return R(b"alice\n" if "find-principals" in args else b"Good signature\n")

    monkeypatch.setattr(trust, "_run", fake_run)
    rec = records.seal_record({**BODY, "schema": records.APPROVAL_SCHEMA_V2,
                               "signer": {"fingerprint": fp, "key_type": key_type}})
    rec["signature"] = {"format": "sshsig", "namespace": trust.NAMESPACE, "armored": armored}
    verdict = trust.check_approval(rec)
    assert verdict.ok and verdict.channel == expect
    # a record that merely *says* it is sk-signed gets no such label
    rec2 = {**rec, "channel": "ssh_sig_sk_system_trust"}
    assert trust.check_approval(rec2).channel == expect


# --------------------------------------------------------------------------- CLI

def _claim_session(sid: str, monkeypatch, tmp_path: Path) -> str:
    from ai_hydro.approval.records import session_claim_revision
    from test_approval import _claim

    monkeypatch.setattr(store, "_SESSIONS_DIR", tmp_path / ".aihydro" / "sessions")
    s = HydroSession(sid)
    s.claims["c1"] = _claim()
    s.save()
    return session_claim_revision(HydroSession.load(sid), "c1")[-1]


def _drive_cli(args: list, tmp_path: Path, rev: str, env_extra: dict) -> tuple:
    import pty

    env = {**os.environ, "HOME": str(tmp_path), "AIHYDRO_HOME": str(tmp_path / "state"),
           "AIHYDRO_SYSTEM_TRUST_FILE": str(tmp_path / "etc" / "allowed_signers"),
           "PYTHONPATH": os.pathsep.join(filter(None, [str(REPO), os.environ.get("PYTHONPATH", "")])),
           **env_extra}
    env.pop("SSH_AUTH_SOCK", None)
    if "AIHYDRO_REQUIRE_SIGNED" not in env_extra:
        env.pop("AIHYDRO_REQUIRE_SIGNED", None)       # approval_helpers sets the dev opt-out at import
    master, slave = pty.openpty()
    proc = subprocess.Popen([sys.executable, "-m", "ai_hydro.approval.cli", *args],
                            stdin=slave, stdout=slave, stderr=slave, env=env, cwd=str(REPO), close_fds=True)
    os.close(slave)
    seen, typed, deadline = b"", False, time.time() + 120
    while time.time() < deadline:
        ready, _, _ = select.select([master], [], [], 0.5)
        if ready:
            try:
                chunk = os.read(master, 4096)
            except OSError:
                break
            if not chunk:
                break
            seen += chunk
        if not typed and b"hex characters" in seen:
            os.write(master, (rev.split(":")[1][:12] + "\n").encode())
            typed = True
        if proc.poll() is not None and not ready:
            break
    code = proc.wait(timeout=30)
    os.close(master)
    return code, seen.decode(errors="replace")


@pytest.mark.skipif(os.name != "posix", reason="needs a POSIX pseudo-terminal")
def test_pty_bypass_with_no_key_available_yields_no_signed_record(scratch_home, monkeypatch):
    """Skeptic's forgery: drive the CLI through a pty. With a trust root and no usable key, no record."""
    rev = _claim_session("pty-nokey", monkeypatch, scratch_home)
    other = make_key(scratch_home / "elsewhere")              # a trust root exists; its key is not in ~/.ssh
    (scratch_home / "state" / "trust").mkdir(parents=True)
    (scratch_home / "state" / "trust" / "allowed_signers").write_text(
        enrol_line(read_pubkey_file(Path(f"{other}.pub")), "alice") + "\n")
    code, out = _drive_cli(["pty-nokey", "c1", "--approver", "mallory"], scratch_home, rev, {})
    assert code == 5, out
    assert "no approval recorded" in out and "fail closed" in out
    monkeypatch.setenv("AIHYDRO_HOME", str(scratch_home / "state"))
    assert approvals_lines() == []


@pytest.mark.skipif(os.name != "posix", reason="needs a POSIX pseudo-terminal")
def test_pty_without_trust_root_fails_closed_and_opt_out_writes_a_labelled_legacy_record(scratch_home, monkeypatch):
    rev = _claim_session("pty-legacy", monkeypatch, scratch_home)
    code, out = _drive_cli(["pty-legacy", "c1", "--approver", "mallory"], scratch_home, rev, {})
    assert code == 5, out                                         # G2: nothing recorded, enrol first
    monkeypatch.setenv("AIHYDRO_HOME", str(scratch_home / "state"))
    assert approvals_lines() == []
    code, out = _drive_cli(["pty-legacy", "c1", "--approver", "mallory"], scratch_home, rev,
                           {"AIHYDRO_REQUIRE_SIGNED": "0"})
    assert code == 0 and "UNSIGNED" in out, out
    lines = approvals_lines()
    assert [x["schema"] for x in lines] == ["aihydro.approval/1"]
    assert not any(str(x.get("channel", "")).startswith("ssh_sig") for x in lines)
    monkeypatch.setenv("AIHYDRO_REQUIRE_SIGNED", "0")
    assert verified_channel(find_approval("pty-legacy", "c1", rev)) == "cli_same_user"


@pytest.mark.skipif(os.name != "posix", reason="needs a POSIX pseudo-terminal")
def test_pty_with_enrolled_key_records_a_signed_approval(scratch_home, monkeypatch):
    rev = _claim_session("pty-key", monkeypatch, scratch_home)
    key = make_key(scratch_home / ".ssh", "id_ed25519")
    home = scratch_home / "state"
    line = enrol_line(read_pubkey_file(Path(f"{key}.pub")), "alice")
    (home / "trust").mkdir(parents=True)
    (home / "trust" / "allowed_signers").write_text(line + "\n")
    code, out = _drive_cli(["pty-key", "c1", "--approver", "alice"], scratch_home, rev, {})
    assert code == 0 and "Approved and signed" in out, out
    monkeypatch.setenv("AIHYDRO_HOME", str(home))
    found = find_approval("pty-key", "c1", rev)
    assert found["schema"] == "aihydro.approval/2" and verified_channel(found) == "ssh_sig_user_trust"


def test_enroll_prints_and_only_writes_with_user_trust(scratch_home):
    key = make_key(scratch_home / "keys")
    out, err = _Sink(), _Sink()
    assert approve_cli(["enroll", f"{key}.pub", "--principal", "alice", "--valid-before", "20300101"],
                       stdout=out, stderr=err) == 0
    text = out.getvalue()
    assert "sudo tee -a /etc/aihydro/allowed_signers" in text
    assert 'namespaces="aihydro-approval@v1"' in text and 'valid-before="20300101"' in text
    assert not trust.user_trust_file().exists()
    out = _Sink()
    assert approve_cli(["enroll", f"{key}.pub", "--user-trust"], stdout=out, stderr=err) == 0
    assert trust.user_trust_file().is_file() and oct(trust.user_trust_file().stat().st_mode & 0o777) == "0o600"
    assert approve_cli(["enroll", str(key)], stdout=_Sink(), stderr=err) == 2     # private key refused
    assert "private key" in err.getvalue()


def test_revoke_rejects_a_malformed_fingerprint(scratch_home):
    assert approve_cli(["revoke", "nonsense"], stdout=_Sink(), stderr=_Sink()) == 2
    assert not trust.revocations_file().exists()


def test_resolve_key_without_any_key_fails_loudly(scratch_home):
    from ai_hydro.approval.signing import SigningError

    with pytest.raises(SigningError, match="no signing key available"):
        resolve_key(None)
