#!/usr/bin/env python3
"""
AI-Hydro capsule verifier — replay.py

Generated by ai_hydro.mcp.tools_session.export_session. Standard library only;
it does not import ai_hydro.

This script checks the archive. It does NOT re-run any computation, and it
prints exactly which level it reached:

    archive_integrity  every file matches its recorded SHA-256 and every v2
                       run record verifies (record seal and the binding to its
                       run-log row). Says nothing about whether the numbers
                       would be produced again.
    cross_check        (--live, at least one comparison, all passed) numeric
                       outputs in run_log.json agree with the values retained
                       in session.json. Still no recomputation.
    not_performed      an integrity check failed; no level is established.

Usage:
    python replay.py                     # archive integrity
    python replay.py --live              # also cross-check run log vs session
    python replay.py --tolerance=0.02    # allow 2% deviation (default 1%)
    python replay.py --allowed-signers FILE
                                         # verify approval signatures against
                                         # a key file YOU supply (for example
                                         # the owner's published GitHub keys)

Approvals (approvals/ in the capsule) are verified only against the signer file
you pass; the capsule carries no trust root and the exporting machine's is not
consulted. Without --allowed-signers each signed approval is reported "not
verified" and never PASS. Requires ssh-keygen (OpenSSH 8.0+) on PATH.

Exit code: 0 = all checks passed, 1 = a check failed (including any approval),
           2 = --live found no comparable values (nothing was cross-checked).
"""
from __future__ import annotations

import decimal
import hashlib
import json
import base64
import math
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

MANIFEST_FILE = "capsule_manifest.json"
DEFAULT_TOLERANCE = 0.01

# Legacy exports (and hand-built fixtures) keep slots under session["slots"].
_LEGACY_TOOL_TO_SLOT = {
    "extract_hydrological_signatures": "signatures",
    "extract_geomorphic_parameters": "geomorphic",
    "compute_twi": "twi",
    "separate_baseflow": "baseflow",
    "train_hydro_model": "model",
    "get_model_results": "model",
    "delineate_watershed": "watershed",
    "delineate_watershed_from_point": "watershed",
    "fetch_streamflow_data": "streamflow",
}


# --------------------------------------------------------------------------- #
# aihydro.c14n/1 for JSON-native values (record dicts read back from JSON):
# tagging (non-finite floats, ints beyond 2**53, "$"-keyed dicts) followed by
# RFC 8785 (JCS) serialisation. Copied from aihydro_core.records.canonical;
# tests assert it reproduces core's golden vectors and digests.
# --------------------------------------------------------------------------- #

_MAX_SAFE_INT = 2 ** 53


def _encode(value):
    if value is None or isinstance(value, (bool, str)):
        return value
    if isinstance(value, int):
        if -_MAX_SAFE_INT <= value <= _MAX_SAFE_INT:
            return value
        return {"$int": str(int(value))}
    if isinstance(value, float):
        if math.isnan(value):
            return {"$float": "nan"}
        if math.isinf(value):
            return {"$float": "inf" if value > 0 else "-inf"}
        return float(value)
    if isinstance(value, dict):
        out = {}
        for key, item in value.items():
            skey = key if isinstance(key, str) else str(key)
            out[skey] = _encode(item)
        if any(k.startswith("$") for k in out):
            return {"$map": out}
        return out
    if isinstance(value, (list, tuple)):
        return [_encode(v) for v in value]
    raise TypeError(f"cannot encode {type(value).__name__}")


def _es_number(x):
    """ECMAScript Number::toString for a finite double (RFC 8785 3.2.2.3)."""
    if x == 0:
        return "0"
    if x < 0:
        return "-" + _es_number(-x)
    sign, digit_tuple, exp = decimal.Decimal(repr(x)).as_tuple()
    digits = "".join(map(str, digit_tuple)).rstrip("0") or "0"
    k = len(digits)
    n = len(digit_tuple) + exp
    if k <= n <= 21:
        return digits + "0" * (n - k)
    if 0 < n <= 21:
        return digits[:n] + "." + digits[n:]
    if -6 < n <= 0:
        return "0." + "0" * (-n) + digits
    e = n - 1
    exp_str = ("+" if e >= 0 else "-") + str(abs(e))
    if k == 1:
        return digits + "e" + exp_str
    return digits[0] + "." + digits[1:] + "e" + exp_str


_ESCAPES = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _es_string(s):
    out = ['"']
    for ch in s:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _serialize(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return _es_number(v)
    if isinstance(v, str):
        return _es_string(v)
    if isinstance(v, list):
        return "[" + ",".join(_serialize(i) for i in v) + "]"
    items = sorted(v.items(), key=lambda kv: kv[0].encode("utf-16-be", "surrogatepass"))
    return "{" + ",".join(_es_string(k) + ":" + _serialize(val) for k, val in items) + "}"


def canonical_bytes(value) -> bytes:
    return _serialize(_encode(value)).encode("utf-8")


def c14n_digest(value) -> str:
    return "sha256:" + hashlib.sha256(canonical_bytes(value)).hexdigest()


_RECORD_DEFAULTS = (
    ("schema", "aihydro.run/2"), ("canonicalization", "aihydro.c14n/1"),
    ("status", "ok"), ("input_refs", []), ("parents", []), ("extra", {}),
)


def record_seal_ok(record: dict) -> bool:
    """True iff ``record`` is sealed and unchanged (mirrors RunRecord.verify)."""
    declared = record.get("record_digest")
    if not declared:
        return False
    payload = {k: v for k, v in record.items() if k != "record_digest" and v is not None}
    for name, default in _RECORD_DEFAULTS:
        payload.setdefault(name, default)
    try:
        return c14n_digest(payload) == declared
    except Exception:
        return False


def verify_run_log(run_log: dict) -> dict:
    """Verify every v2 record in a run log. Rows without a record are legacy."""
    summary = {"rows": 0, "v2_records": 0, "verified": 0, "unbound": 0, "legacy": 0,
               "record_errors": 0, "redacted": 0, "failures": []}
    for run_id, entry in sorted(run_log.items()):
        summary["rows"] += 1
        if isinstance(entry, dict) and entry.get("redacted_for_privacy"):
            # Legacy sealed row withheld on export (it held a local path): neither verified nor failed.
            summary["redacted"] += 1
            continue
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict):
            summary["legacy"] += 1
            continue
        summary["v2_records"] += 1
        if record.get("record_error"):
            summary["record_errors"] += 1
        if record.get("run_id") != run_id:
            summary["failures"].append((run_id, "record.run_id does not match its row"))
            continue
        if not record_seal_ok(record):
            summary["failures"].append((run_id, "record_digest mismatch"))
            continue
        expected = (record.get("extra") or {}).get("entry_digest")
        if expected is None:
            summary["unbound"] += 1     # sealed but not bound to its row: not "verified"
            continue
        if expected is not None:
            body = {k: v for k, v in entry.items() if k != "record"}
            try:
                actual = c14n_digest(body)
            except Exception:
                actual = None
            if actual != expected:
                summary["failures"].append((run_id, "run-log row changed after its record was sealed"))
                continue
        summary["verified"] += 1
    return summary


# --------------------------------------------------------------------------- #
# File hashes
# --------------------------------------------------------------------------- #

def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_hashes(capsule_dir: Path, out=print):
    manifest_path = capsule_dir / MANIFEST_FILE
    if not manifest_path.exists():
        out(f"FAIL  {MANIFEST_FILE} not found")
        return False, []
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    results = []
    for entry in manifest["files"]:
        fpath = capsule_dir / entry["path"]
        if not fpath.exists():
            out(f"MISS  {entry['path']}")
            results.append({"path": entry["path"], "status": "missing"})
            continue
        actual = _sha256(fpath)
        ok = actual == entry["sha256"]
        detail = "" if ok else f"  expected={entry['sha256'][:12]}...  actual={actual[:12]}..."
        out(f"{'PASS' if ok else 'FAIL'}  {entry['path']}{detail}")
        results.append({"path": entry["path"], "status": "pass" if ok else "fail"})
    return all(r["status"] == "pass" for r in results), results


# --------------------------------------------------------------------------- #
# Served data: bind data/ files to the producer's SEALED record
# --------------------------------------------------------------------------- #

def _retained_name(path: str) -> str:
    # "session-data:<file>" / "workspace:<rel>" refs (and legacy absolute paths)
    for scheme in ("session-data:", "workspace:"):
        if path.startswith(scheme):
            path = path[len(scheme):]
            break
    return Path(path).name.split(".data.", 1)[-1]


def _csv_matches_json(csv_path: Path, json_path: Path) -> bool:
    """The derived CSV holds exactly the retained JSON's dates and q_cms."""
    try:
        body = json.loads(json_path.read_text(encoding="utf-8"))
        lines = csv_path.read_text(encoding="utf-8").splitlines()
        if lines[0].split(",") != ["date", "q_cms"]:
            return False
        rows = [ln.split(",") for ln in lines[1:]]
        dates, q = body["dates"], body["q_cms"]
        if len(rows) != len(dates):
            return False
        for (d, v), d0, v0 in zip(rows, dates, q):
            if d != str(d0) or (v == "") != (v0 is None) or (v != "" and float(v) != float(v0)):
                return False
        return True
    except Exception:
        return False


def verify_data_bindings(capsule_dir: Path, out=print) -> bool:
    """Check retained data files against digests sealed in producer records.

    Reads run_log.json (not the manifest), so a regenerated manifest cannot
    hide a swapped series. A record whose seal fails is ignored here; the
    record check reports it. Files with no sealed digest are reported as
    self-attested, never as bound.
    """
    ok = True
    rl_path = capsule_dir / "run_log.json"
    run_log = json.loads(rl_path.read_text(encoding="utf-8")) if rl_path.exists() else {}
    sealed_names = set()
    for run_id, entry in sorted(run_log.items()):
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict) or not record_seal_ok(record):
            continue
        for f in (record.get("extra") or {}).get("retained_files") or []:
            if not (isinstance(f, dict) and f.get("path") and f.get("digest")):
                continue
            name = _retained_name(f["path"])
            fpath = capsule_dir / "data" / name
            if not fpath.exists():
                if f"data/{name}" in _listed_data_paths(capsule_dir):
                    # The manifest says the capsule carries this evidence; its
                    # absence is a deletion, which must fail like a swap.
                    ok = False
                    out(f"FAIL  data/{name}: sealed by {run_id} and listed in the manifest, but missing")
                else:
                    out(f"NOTE  data/{name}: sealed by {run_id} but not in this capsule")
                continue
            sealed_names.add(f"data/{name}")
            actual = "sha256:" + _sha256(fpath)
            if actual == f["digest"]:
                out(f"PASS  data/{name} matches the digest sealed by {run_id}")
            else:
                ok = False
                out(f"FAIL  data/{name} differs from the digest sealed by {run_id}")
    try:
        manifest = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        manifest = {}
    for art in manifest.get("data_artifacts") or []:
        ra = (art.get("retained_artifact") or {}).get("path")
        if art.get("binding") == "producer_sealed" and ra not in sealed_names:
            ok = False
            out(f"FAIL  {art.get('path')} claims a producer-sealed binding but no sealed record "
                f"names {ra}")
        elif art.get("path") and art.get("binding") != "producer_sealed":
            out(f"NOTE  {art['path']}: {art.get('binding', 'self_attested')} "
                f"({art.get('status')}); no sealed producer digest names this series")
        if art.get("path") and ra:
            if (capsule_dir / ra).exists() and (capsule_dir / art["path"]).exists():
                if _csv_matches_json(capsule_dir / art["path"], capsule_dir / ra):
                    out(f"PASS  {art['path']} equals the retained series {ra}")
                else:
                    ok = False
                    out(f"FAIL  {art['path']} does not equal the retained series {ra}")
    return ok


# --------------------------------------------------------------------------- #
# Approvals: verify signed human approvals against a SUPPLIED signer file
# --------------------------------------------------------------------------- #

APPROVAL_NAMESPACE = "aihydro-approval@v1"
APPROVALS_INDEX = "approvals/index.json"


def _sshsig_key(armored: str):
    """``(key_type, fingerprint, namespace)`` from an armored SSHSIG, or None."""
    try:
        lines = [ln.strip() for ln in armored.strip().splitlines()]
        if lines[0] != "-----BEGIN SSH SIGNATURE-----" or lines[-1] != "-----END SSH SIGNATURE-----":
            return None
        blob = base64.b64decode("".join(lines[1:-1]), validate=True)
        if blob[:6] != b"SSHSIG":
            return None

        def read(buf, off):
            (n,) = struct.unpack_from(">I", buf, off)
            return buf[off + 4: off + 4 + n], off + 4 + n

        pub, off = read(blob, 10)
        ns, _ = read(blob, off)
        ktype, _ = read(pub, 0)
        fp = "SHA256:" + base64.b64encode(hashlib.sha256(pub).digest()).decode().rstrip("=")
        return ktype.decode("ascii"), fp, ns.decode("utf-8")
    except Exception:
        return None


def _ssh_verify(record: dict, signers: Path):
    """``(ok, reason)`` from ``ssh-keygen -Y verify`` over the sealed digest."""
    exe = shutil.which("ssh-keygen")
    if exe is None:
        return False, "ssh-keygen not found on PATH"
    principal = (record.get("approver") or {}).get("id")
    if not principal:
        return False, "approval has no approver id"
    with tempfile.TemporaryDirectory(prefix="aihydro-replay-") as tmp:
        sig = Path(tmp) / "approval.sig"
        sig.write_text(record["signature"]["armored"].strip() + "\n", encoding="utf-8")
        try:
            res = subprocess.run(
                [exe, "-Y", "verify", "-f", str(signers), "-I", principal,
                 "-n", APPROVAL_NAMESPACE, "-s", str(sig)],
                input=record["record_digest"].encode("utf-8"), capture_output=True, timeout=30)
        except (OSError, subprocess.SubprocessError) as exc:
            return False, f"ssh-keygen failed: {exc}"
    if res.returncode == 0:
        return True, "signature verifies"
    msg = (res.stderr or res.stdout).decode("utf-8", "replace").strip().splitlines()
    return False, f"signature not accepted for principal {principal!r}: {msg[0] if msg else 'verify failed'}"


_APPROVAL_FILE_RE = re.compile(r"^approvals/([0-9a-f]{64})\.json$")
REVISION_SCHEMA = "aihydro.claim_revision/2"


def _run_fingerprint(record: dict) -> str:
    """``registry.evidence.fingerprint``: sha256-v2 of the sorted, compact JSON of a run row."""
    payload = json.dumps(record, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return "sha256-v2:" + hashlib.sha256(payload.encode()).hexdigest()


def recompute_claim_revision(session_raw: dict, run_log: dict, claim_id: str):
    """``(claim_revision_digest, None)`` recomputed from the capsule, or ``(None, reason)``.

    Mirrors ``ai_hydro.approval.records.claim_revision_fields`` for claims whose
    evidence spans are all run-backed (the retained run row is in ``run_log.json``).
    Anything not reproducible in stdlib returns a precise reason, never a digest:
    dataset and paper spans (they need the raw slot / the passage index), legacy
    ``evidence`` lists, claims that are not valid scientific claims.
    """
    claims = session_raw.get("claims")
    claim = claims.get(claim_id) if isinstance(claims, dict) else None
    if not isinstance(claim, dict):
        return None, f"claim {claim_id!r} is not in session.json"
    if claim.get("evidence") and "evidence_spans" not in claim:
        return None, "claim uses the legacy 'evidence' list; its revision is not reproducible in stdlib"
    scope = claim.get("scope")
    rationale = claim.get("confidence_rationale")
    if (not isinstance(scope, dict) or not isinstance(scope.get("basins"), list)
            or not isinstance(scope.get("period"), str) or not isinstance(claim.get("claim"), str)
            or not all(isinstance(claim.get(k), str) for k in ("claim_type", "status", "confidence"))
            or not isinstance(rationale, str) or len(rationale.strip()) < 20):
        return None, "claim in session.json is not a valid scientific claim"
    spans = claim.get("evidence_spans") or []
    session_id = session_raw.get("session_id")
    norm_spans, versions = [], {}
    for span in spans:
        if not isinstance(span, dict) or not span.get("source_type") or not span.get("source_id"):
            return None, "claim has a malformed evidence span"
        kind, sid = span["source_type"], span["source_id"]
        if kind != "run":
            return None, (f"evidence span {sid!r} is a {kind} span; its fingerprint needs "
                          f"{'the raw session slot' if kind == 'dataset' else 'the passage index'}, "
                          "not reproducible in stdlib from the capsule")
        row = run_log.get(sid) if isinstance(run_log, dict) else None
        if isinstance(row, dict) and row.get("redacted_for_privacy"):
            return None, f"run {sid!r} is redacted for privacy (not verifiable from capsule)"
        if not isinstance(row, dict) or not row:
            return None, f"run {sid!r} cited by the claim is not retained in run_log.json"
        if row.get("session_id", session_id) != session_id or row.get("run_id", sid) != sid:
            return None, f"run {sid!r} has conflicting session/run identity"
        versions[sid] = _run_fingerprint(row)
        norm_spans.append({"source_type": kind, "source_id": sid, "metric_ref": span.get("metric_ref"),
                           "page": span.get("page"), "passage_hash": span.get("passage_hash")})
    out_scope = {"basins": list(scope["basins"]), "period": scope["period"],
                 "forcing": scope.get("forcing"), "metric": scope.get("metric"),
                 "model_versions": scope.get("model_versions") or {}}
    if scope.get("basin_refs") is not None:     # same omission-when-None rule as ClaimScope (slice 3)
        out_scope["basin_refs"] = [dict(e) for e in scope["basin_refs"]]
    fields = {
        "schema": REVISION_SCHEMA,
        "text": claim["claim"],
        "claim_type": claim["claim_type"],
        "status": claim["status"],
        "confidence": claim["confidence"],
        "confidence_rationale": rationale,
        "scope": out_scope,
        "evidence_spans": norm_spans,
        "evidence_versions": versions,
        "limitations": list(claim.get("limitations") or []),
        "prereg_id": claim.get("prereg_id"),
        "uncertainty_verified": bool(claim.get("uncertainty_verified")),
    }
    try:
        return c14n_digest(fields), None
    except Exception as exc:
        return None, f"claim revision could not be encoded: {exc}"


def _approval_path(capsule_dir: Path, rel, digest):
    """The approval file iff ``rel`` is exactly ``approvals/<hex>.json`` for ``digest`` and a real file inside the capsule."""
    m = _APPROVAL_FILE_RE.match(rel) if isinstance(rel, str) else None
    if m is None or digest != "sha256:" + m.group(1):
        return None
    d, f = capsule_dir / "approvals", capsule_dir / rel
    if d.is_symlink() or f.is_symlink() or not f.is_file():
        return None
    return f if f.resolve().parent == d.resolve() else None


def verify_approvals(capsule_dir: Path, allowed_signers=None, out=print) -> dict:
    """Check every approval the capsule carries.

    Per approval: the sealed body digest, the binding of ``claim_revision_digest``
    to the registry stamp, and (v2 with ``allowed_signers``) the SSHSIG under the
    supplied file, namespace ``aihydro-approval@v1`` and principal = approver id.
    Without a signer file a signed approval is "not verified", never PASS.
    Returns counts; ``failed > 0`` means exit 1.
    """
    c = {"verified": 0, "failed": 0, "unsigned": 0, "unverified": 0, "no_approval": 0, "claims": 0}
    index_path = capsule_dir / APPROVALS_INDEX
    if not index_path.exists():
        out("Approvals: none in this capsule (no promoted claims were exported)")
        return c
    try:
        index = json.loads(index_path.read_text(encoding="utf-8"))
        claims = index["claims"]
    except Exception:
        out(f"FAIL  {APPROVALS_INDEX} is unreadable")
        c["failed"] += 1
        return c
    try:
        session_raw = json.loads((capsule_dir / "session.json").read_text(encoding="utf-8"))
        session_raw = session_raw if isinstance(session_raw, dict) else {}
    except Exception:
        session_raw = {}
    try:
        run_log = json.loads((capsule_dir / "run_log.json").read_text(encoding="utf-8"))
    except Exception:
        run_log = {}
    signers = Path(allowed_signers) if allowed_signers else None
    if signers is not None and not signers.is_file():
        out(f"FAIL  --allowed-signers file not found: {signers}")
        c["failed"] += 1
        signers = None
    for e in claims:
        c["claims"] += 1
        label = f"{e.get('claim_id')} ({e.get('registry_id') or 'no registry id'})"
        status = e.get("status")
        if status == "no_approval":
            c["no_approval"] += 1
            out(f"NOTE  approval {label}: no approval record ({e.get('reason', 'self_asserted')}); not approved")
            continue
        if status != "record_carried":
            c["failed"] += 1
            out(f"FAIL  approval {label}: {e.get('reason') or status}")
            continue
        path = _approval_path(capsule_dir, e.get("approval_file"), e.get("record_digest"))
        if path is None:
            c["failed"] += 1
            out(f"FAIL  approval {label}: approval file must be approvals/<64 hex>.json named by its "
                f"record digest, a regular file inside the capsule (got {e.get('approval_file')!r})")
            continue
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            c["failed"] += 1
            out(f"FAIL  approval {label}: record file {e.get('approval_file')} unreadable")
            continue
        v2 = record.get("schema") == "aihydro.approval/2"
        skip = {"record_digest", "signature"} if v2 else {"record_digest"}
        try:
            sealed = c14n_digest({k: v for k, v in record.items() if k not in skip}) == record.get("record_digest")
        except Exception:
            sealed = False
        stamp = (e.get("registry_stamp") or {})
        problems = []
        if not sealed:
            problems.append("sealed body digest mismatch (record altered)")
        if record.get("record_digest") != e.get("record_digest") \
                or record.get("record_digest") != (stamp.get("approval") or {}).get("record_digest"):
            problems.append("record_digest differs from the registry stamp's")
        if not stamp.get("claim_revision_digest") \
                or record.get("claim_revision_digest") != stamp.get("claim_revision_digest"):
            problems.append("claim_revision_digest differs from the registry stamp's")
        if record.get("claim_id") != e.get("claim_id"):
            problems.append(f"the record approves claim {record.get('claim_id')!r}, not "
                            f"{e.get('claim_id')!r}")
        sess_ids = {record.get("session_id"), index.get("session_id"), session_raw.get("session_id")}
        if len(sess_ids) != 1 or None in sess_ids:
            problems.append("session id differs between the approval record "
                            f"({record.get('session_id')!r}), the approvals index "
                            f"({index.get('session_id')!r}) and session.json ({session_raw.get('session_id')!r})")
        approver = record.get("approver")
        if not isinstance(approver, dict) or approver.get("kind") != "human" or not approver.get("id"):
            problems.append("approver is not a human actor")
        if not problems:
            recomputed, why = recompute_claim_revision(session_raw, run_log, record["claim_id"])
            if recomputed is None:
                problems.append(f"claim revision cannot be re-derived from the capsule: {why}")
            elif recomputed != record["claim_revision_digest"]:
                problems.append("the claim (or the run rows it cites) in this capsule is not the revision "
                                "the approval signed: recomputed claim_revision_digest differs")
        if problems:
            c["failed"] += 1
            out(f"FAIL  approval {label}: " + "; ".join(problems))
            continue
        if not v2:
            c["unsigned"] += 1
            out(f"UNSIGNED  approval {label}: v1 record (cli_same_user); sealed and bound to its "
                f"claim revision, but no signature exists to verify")
            continue
        sig = record.get("signature") or {}
        parsed = _sshsig_key(sig.get("armored", "")) if isinstance(sig.get("armored"), str) else None
        signer = record.get("signer") or {}
        if sig.get("namespace") != APPROVAL_NAMESPACE or parsed is None or parsed[2] != APPROVAL_NAMESPACE:
            c["failed"] += 1
            out(f"FAIL  approval {label}: missing or malformed signature (namespace {APPROVAL_NAMESPACE})")
            continue
        if parsed[1] != signer.get("fingerprint") or parsed[0] != signer.get("key_type"):
            c["failed"] += 1
            out(f"FAIL  approval {label}: signature key does not match the sealed signer")
            continue
        if signers is None:
            c["unverified"] += 1
            if allowed_signers:
                continue
            out(f"NOTE  approval {label}: not verified (no signer file supplied); "
                f"signer {signer.get('fingerprint')}")
            continue
        ok, why = _ssh_verify(record, signers)
        if ok:
            c["verified"] += 1
            out(f"PASS  approval {label}: {why}; approver {record['approver']['id']}, "
                f"signer {signer.get('fingerprint')}")
        else:
            c["failed"] += 1
            out(f"FAIL  approval {label}: {why}")
    if allowed_signers:
        out(f"approvals: {c['verified']} verified against supplied signers, {c['failed']} failed, "
            f"{c['unsigned']} unsigned (cli_same_user/opt-out)")
    else:
        out(f"approvals: {c['unverified']} not verified (no signer file supplied), {c['failed']} failed, "
            f"{c['unsigned']} unsigned (cli_same_user/opt-out)")
    if c["no_approval"]:
        out(f"claims without an approval record: {c['no_approval']}")
    return c


# --------------------------------------------------------------------------- #
# Live cross-check: run log vs the values retained in session.json
# --------------------------------------------------------------------------- #

def _slot_results(raw: dict) -> list:
    """Every retained slot result as ``(slot, result_dict)``.

    Real exports store slots as top-level keys shaped
    ``{feature_id: {params_key: {"data":..., "meta":...}}}`` (flag
    ``_hydro_slots_v2``). Older fixtures put ``{"data":...}`` under
    ``session["slots"][slot]``; both are read.
    """
    found = []
    legacy = raw.get("slots")
    if isinstance(legacy, dict):
        for slot, result in legacy.items():
            if isinstance(result, dict):
                found.append((slot, result))
    for slot, value in raw.items():
        if slot == "slots" or not isinstance(value, dict):
            continue
        if not (raw.get("_hydro_slots_v2") or "__legacy__" in value):
            continue
        for by_key in value.values():
            if not isinstance(by_key, dict):
                continue
            for result in by_key.values():
                if isinstance(result, dict) and isinstance(result.get("data"), dict):
                    found.append((slot, result))
    return found


def _computed_at(result: dict) -> str:
    meta = result.get("meta")
    return str(meta.get("computed_at", "")) if isinstance(meta, dict) else ""


def _candidate(entry: dict, run_id: str, results: list, is_latest_for_tool: bool):
    """The retained result a run-log row can honestly be compared with."""
    exact = [r for _, r in results
             if isinstance(r.get("meta"), dict) and r["meta"].get("run_id") == run_id]
    if exact:
        return exact[0], "run_id"
    if not is_latest_for_tool:
        return None, "superseded by a later run of the same tool"
    tool = entry.get("tool_name", "")
    same_tool = [r for _, r in results
                 if isinstance(r.get("meta"), dict) and r["meta"].get("tool") == tool]
    if not same_tool and tool in _LEGACY_TOOL_TO_SLOT:
        same_tool = [r for slot, r in results if slot == _LEGACY_TOOL_TO_SLOT[tool]]
    if not same_tool:
        return None, "no retained result for this tool"
    return max(same_tool, key=_computed_at), "latest result of the same tool"


def live_cross_check(capsule_dir: Path, tolerance: float = DEFAULT_TOLERANCE):
    """Compare numeric ``key_outputs`` with retained slot values.

    Returns ``(comparisons, skipped)``. Each comparison has run_id, key,
    expected, actual, deviation_pct, status. Nothing is recomputed.
    """
    rl_path = capsule_dir / "run_log.json"
    sj_path = capsule_dir / "session.json"
    if not rl_path.exists() or not sj_path.exists():
        return [], [("-", "run_log.json or session.json not found")]
    run_log = json.loads(rl_path.read_text(encoding="utf-8"))
    raw = json.loads(sj_path.read_text(encoding="utf-8"))
    results = _slot_results(raw)

    latest = {}
    for run_id, entry in run_log.items():
        if not isinstance(entry, dict):
            continue
        tool = entry.get("tool_name", "")
        stamp = str(entry.get("timestamp", ""))
        if tool not in latest or (stamp, run_id) > latest[tool]:
            latest[tool] = (stamp, run_id)

    comparisons, skipped = [], []
    for run_id, entry in sorted(run_log.items()):
        if not isinstance(entry, dict):
            continue
        key_outputs = entry.get("key_outputs")
        if not isinstance(key_outputs, dict) or not key_outputs:
            continue
        is_latest = latest.get(entry.get("tool_name", ""), (None, None))[1] == run_id
        result, how = _candidate(entry, run_id, results, is_latest)
        if result is None:
            skipped.append((run_id, how))
            continue
        data = result.get("data") if isinstance(result.get("data"), dict) else {}
        for key, expected in key_outputs.items():
            if key.startswith("_") or isinstance(expected, bool) or not isinstance(expected, (int, float)):
                continue
            actual = data.get(key)
            if isinstance(actual, bool) or not isinstance(actual, (int, float)):
                continue
            if not (math.isfinite(expected) and math.isfinite(actual)):
                continue
            if expected == 0:
                deviation = 0.0 if abs(actual) < 1e-9 else float("inf")
            else:
                deviation = abs(actual - expected) / abs(expected)
            comparisons.append({
                "run_id": run_id, "key": key, "expected": expected, "actual": actual,
                "deviation_pct": round(deviation * 100, 3), "matched_by": how,
                "status": "pass" if deviation <= tolerance else "fail",
            })
    return comparisons, skipped


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #

def replay_status(integrity_ok: bool, live: bool, n_comparisons: int, comparisons_ok: bool) -> str:
    """The strongest level actually reached. Never ``recomputed``."""
    if not integrity_ok:
        return "not_performed"
    if live and n_comparisons > 0 and comparisons_ok:
        return "cross_check"
    return "archive_integrity"


def run(capsule_dir: Path, live: bool = False, tolerance: float = DEFAULT_TOLERANCE, out=print,
        allowed_signers=None) -> int:
    hashes_ok, hash_results = verify_hashes(capsule_dir, out=out)
    n_pass = sum(1 for r in hash_results if r["status"] == "pass")
    n_bad = sum(1 for r in hash_results if r["status"] != "pass")
    out(f"\nHash check: {n_pass} pass, {n_bad} fail")

    records_ok = True
    rl_path = capsule_dir / "run_log.json"
    if rl_path.exists():
        summary = verify_run_log(json.loads(rl_path.read_text(encoding="utf-8")))
        for run_id, why in summary["failures"]:
            out(f"FAIL  record {run_id}: {why}")
        records_ok = not summary["failures"]
        out(f"Run records: {summary['verified']} of {summary['v2_records']} v2 records verify; "
            f"{summary['unbound']} sealed but unbound to their row; "
            f"{summary['legacy']} legacy rows have no record; {summary['record_errors']} carry a record_error")
        if summary["redacted"]:
            out(f"NOTE  {summary['redacted']} run-log row(s) redacted for privacy "
                "(not verifiable from capsule): neither verified nor failed")
    else:
        out("Run records: run_log.json not found")

    bindings_ok = verify_data_bindings(capsule_dir, out=out)

    out("")
    approvals_ok = verify_approvals(capsule_dir, allowed_signers, out=out)["failed"] == 0

    comparisons, comparisons_ok = [], True
    if live:
        comparisons, skipped = live_cross_check(capsule_dir, tolerance)
        for c in comparisons:
            if c["status"] == "pass":
                out(f"PASS  {c['run_id']}:{c['key']}  {c['expected']:.4g} ~ {c['actual']:.4g}")
            else:
                out(f"FAIL  {c['run_id']}:{c['key']}  expected={c['expected']:.4g}  "
                    f"got={c['actual']:.4g}  ({c['deviation_pct']:.1f}%)")
        comparisons_ok = all(c["status"] == "pass" for c in comparisons)
        for run_id, why in skipped:
            out(f"SKIP  {run_id}: {why}")

    integrity_ok = hashes_ok and records_ok and bindings_ok
    if not hash_results and not (rl_path.exists() and summary["v2_records"]):
        integrity_ok = False        # nothing was actually checked
        out("FAIL  archive has no files and no records; nothing was verified.")
    status = replay_status(integrity_ok, live, len(comparisons), comparisons_ok)
    out(f"\nreplay_status: {status}")
    out("recomputation: not_performed")
    if live:
        out(f"comparisons: {len(comparisons)}")

    if not (integrity_ok and comparisons_ok and approvals_ok):
        return 1
    if live and not comparisons:
        out("FAIL  --live found no comparable values; nothing was cross-checked.")
        return 2
    return 0


def main(argv=None, capsule_dir: Path | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    tolerance = DEFAULT_TOLERANCE
    allowed_signers = None
    for i, arg in enumerate(argv):
        if arg.startswith("--tolerance="):
            try:
                tolerance = float(arg.split("=", 1)[1])
            except ValueError:
                pass
        elif arg.startswith("--allowed-signers="):
            allowed_signers = arg.split("=", 1)[1]
        elif arg == "--allowed-signers":
            if i + 1 >= len(argv):
                print("FAIL  --allowed-signers needs a file argument")
                return 1
            allowed_signers = argv[i + 1]
    return run(capsule_dir or Path(__file__).parent, live="--live" in argv, tolerance=tolerance,
               allowed_signers=allowed_signers)


def source_text() -> str:
    """The text written to a capsule as ``replay.py`` (this file, verbatim)."""
    return Path(__file__).read_text(encoding="utf-8")



def _listed_data_paths(capsule_dir: Path) -> set:
    """data/ paths the manifest claims the capsule carries (files + data_artifacts)."""
    try:
        m = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        return set()
    listed = {e.get("path") for e in m.get("files") or [] if isinstance(e, dict)}
    for art in m.get("data_artifacts") or []:
        if isinstance(art, dict):
            listed.add(art.get("path"))
            listed.add(art.get("retained_artifact", {}).get("path") if isinstance(art.get("retained_artifact"), dict) else None)
    return {x for x in listed if isinstance(x, str) and x.startswith("data/")}

if __name__ == "__main__":
    sys.exit(main())
