#!/usr/bin/env python3
"""
AI-Hydro capsule verifier — replay.py

Generated by ai_hydro.mcp.tools_session.export_session. Standard library only;
it does not import ai_hydro.

This script checks the archive. It does NOT re-run any computation, and it
prints exactly which level it reached:

    archive_integrity  every file matches its recorded SHA-256 and every v2
                       run record verifies (record seal and the binding to its
                       run-log row). Says nothing about whether the numbers
                       would be produced again.
    cross_check        (--live, at least one comparison, all passed) numeric
                       outputs in run_log.json agree with the values retained
                       in session.json. Still no recomputation.
    not_performed      an integrity check failed; no level is established.

Usage:
    python replay.py                     # archive integrity
    python replay.py --live              # also cross-check run log vs session
    python replay.py --tolerance=0.02    # allow 2% deviation (default 1%)

Exit code: 0 = all checks passed, 1 = a check failed,
           2 = --live found no comparable values (nothing was cross-checked).
"""
from __future__ import annotations

import decimal
import hashlib
import json
import math
import sys
from pathlib import Path

MANIFEST_FILE = "capsule_manifest.json"
DEFAULT_TOLERANCE = 0.01

# Legacy exports (and hand-built fixtures) keep slots under session["slots"].
_LEGACY_TOOL_TO_SLOT = {
    "extract_hydrological_signatures": "signatures",
    "extract_geomorphic_parameters": "geomorphic",
    "compute_twi": "twi",
    "separate_baseflow": "baseflow",
    "train_hydro_model": "model",
    "get_model_results": "model",
    "delineate_watershed": "watershed",
    "delineate_watershed_from_point": "watershed",
    "fetch_streamflow_data": "streamflow",
}


# --------------------------------------------------------------------------- #
# aihydro.c14n/1 for JSON-native values (record dicts read back from JSON):
# tagging (non-finite floats, ints beyond 2**53, "$"-keyed dicts) followed by
# RFC 8785 (JCS) serialisation. Copied from aihydro_core.records.canonical;
# tests assert it reproduces core's golden vectors and digests.
# --------------------------------------------------------------------------- #

_MAX_SAFE_INT = 2 ** 53


def _encode(value):
    if value is None or isinstance(value, (bool, str)):
        return value
    if isinstance(value, int):
        if -_MAX_SAFE_INT <= value <= _MAX_SAFE_INT:
            return value
        return {"$int": str(int(value))}
    if isinstance(value, float):
        if math.isnan(value):
            return {"$float": "nan"}
        if math.isinf(value):
            return {"$float": "inf" if value > 0 else "-inf"}
        return float(value)
    if isinstance(value, dict):
        out = {}
        for key, item in value.items():
            skey = key if isinstance(key, str) else str(key)
            out[skey] = _encode(item)
        if any(k.startswith("$") for k in out):
            return {"$map": out}
        return out
    if isinstance(value, (list, tuple)):
        return [_encode(v) for v in value]
    raise TypeError(f"cannot encode {type(value).__name__}")


def _es_number(x):
    """ECMAScript Number::toString for a finite double (RFC 8785 3.2.2.3)."""
    if x == 0:
        return "0"
    if x < 0:
        return "-" + _es_number(-x)
    sign, digit_tuple, exp = decimal.Decimal(repr(x)).as_tuple()
    digits = "".join(map(str, digit_tuple)).rstrip("0") or "0"
    k = len(digits)
    n = len(digit_tuple) + exp
    if k <= n <= 21:
        return digits + "0" * (n - k)
    if 0 < n <= 21:
        return digits[:n] + "." + digits[n:]
    if -6 < n <= 0:
        return "0." + "0" * (-n) + digits
    e = n - 1
    exp_str = ("+" if e >= 0 else "-") + str(abs(e))
    if k == 1:
        return digits + "e" + exp_str
    return digits[0] + "." + digits[1:] + "e" + exp_str


_ESCAPES = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _es_string(s):
    out = ['"']
    for ch in s:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _serialize(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return _es_number(v)
    if isinstance(v, str):
        return _es_string(v)
    if isinstance(v, list):
        return "[" + ",".join(_serialize(i) for i in v) + "]"
    items = sorted(v.items(), key=lambda kv: kv[0].encode("utf-16-be", "surrogatepass"))
    return "{" + ",".join(_es_string(k) + ":" + _serialize(val) for k, val in items) + "}"


def canonical_bytes(value) -> bytes:
    return _serialize(_encode(value)).encode("utf-8")


def c14n_digest(value) -> str:
    return "sha256:" + hashlib.sha256(canonical_bytes(value)).hexdigest()


_RECORD_DEFAULTS = (
    ("schema", "aihydro.run/2"), ("canonicalization", "aihydro.c14n/1"),
    ("status", "ok"), ("input_refs", []), ("parents", []), ("extra", {}),
)


def record_seal_ok(record: dict) -> bool:
    """True iff ``record`` is sealed and unchanged (mirrors RunRecord.verify)."""
    declared = record.get("record_digest")
    if not declared:
        return False
    payload = {k: v for k, v in record.items() if k != "record_digest" and v is not None}
    for name, default in _RECORD_DEFAULTS:
        payload.setdefault(name, default)
    try:
        return c14n_digest(payload) == declared
    except Exception:
        return False


def verify_run_log(run_log: dict) -> dict:
    """Verify every v2 record in a run log. Rows without a record are legacy."""
    summary = {"rows": 0, "v2_records": 0, "verified": 0, "unbound": 0, "legacy": 0,
               "record_errors": 0, "failures": []}
    for run_id, entry in sorted(run_log.items()):
        summary["rows"] += 1
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict):
            summary["legacy"] += 1
            continue
        summary["v2_records"] += 1
        if record.get("record_error"):
            summary["record_errors"] += 1
        if record.get("run_id") != run_id:
            summary["failures"].append((run_id, "record.run_id does not match its row"))
            continue
        if not record_seal_ok(record):
            summary["failures"].append((run_id, "record_digest mismatch"))
            continue
        expected = (record.get("extra") or {}).get("entry_digest")
        if expected is None:
            summary["unbound"] += 1     # sealed but not bound to its row: not "verified"
            continue
        if expected is not None:
            body = {k: v for k, v in entry.items() if k != "record"}
            try:
                actual = c14n_digest(body)
            except Exception:
                actual = None
            if actual != expected:
                summary["failures"].append((run_id, "run-log row changed after its record was sealed"))
                continue
        summary["verified"] += 1
    return summary


# --------------------------------------------------------------------------- #
# File hashes
# --------------------------------------------------------------------------- #

def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_hashes(capsule_dir: Path, out=print):
    manifest_path = capsule_dir / MANIFEST_FILE
    if not manifest_path.exists():
        out(f"FAIL  {MANIFEST_FILE} not found")
        return False, []
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    results = []
    for entry in manifest["files"]:
        fpath = capsule_dir / entry["path"]
        if not fpath.exists():
            out(f"MISS  {entry['path']}")
            results.append({"path": entry["path"], "status": "missing"})
            continue
        actual = _sha256(fpath)
        ok = actual == entry["sha256"]
        detail = "" if ok else f"  expected={entry['sha256'][:12]}...  actual={actual[:12]}..."
        out(f"{'PASS' if ok else 'FAIL'}  {entry['path']}{detail}")
        results.append({"path": entry["path"], "status": "pass" if ok else "fail"})
    return all(r["status"] == "pass" for r in results), results


# --------------------------------------------------------------------------- #
# Served data: bind data/ files to the producer's SEALED record
# --------------------------------------------------------------------------- #

def _retained_name(path: str) -> str:
    # "session-data:<file>" / "workspace:<rel>" refs (and legacy absolute paths)
    for scheme in ("session-data:", "workspace:"):
        if path.startswith(scheme):
            path = path[len(scheme):]
            break
    return Path(path).name.split(".data.", 1)[-1]


def _csv_matches_json(csv_path: Path, json_path: Path) -> bool:
    """The derived CSV holds exactly the retained JSON's dates and q_cms."""
    try:
        body = json.loads(json_path.read_text(encoding="utf-8"))
        lines = csv_path.read_text(encoding="utf-8").splitlines()
        if lines[0].split(",") != ["date", "q_cms"]:
            return False
        rows = [ln.split(",") for ln in lines[1:]]
        dates, q = body["dates"], body["q_cms"]
        if len(rows) != len(dates):
            return False
        for (d, v), d0, v0 in zip(rows, dates, q):
            if d != str(d0) or (v == "") != (v0 is None) or (v != "" and float(v) != float(v0)):
                return False
        return True
    except Exception:
        return False


def verify_data_bindings(capsule_dir: Path, out=print) -> bool:
    """Check retained data files against digests sealed in producer records.

    Reads run_log.json (not the manifest), so a regenerated manifest cannot
    hide a swapped series. A record whose seal fails is ignored here; the
    record check reports it. Files with no sealed digest are reported as
    self-attested, never as bound.
    """
    ok = True
    rl_path = capsule_dir / "run_log.json"
    run_log = json.loads(rl_path.read_text(encoding="utf-8")) if rl_path.exists() else {}
    sealed_names = set()
    for run_id, entry in sorted(run_log.items()):
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict) or not record_seal_ok(record):
            continue
        for f in (record.get("extra") or {}).get("retained_files") or []:
            if not (isinstance(f, dict) and f.get("path") and f.get("digest")):
                continue
            name = _retained_name(f["path"])
            fpath = capsule_dir / "data" / name
            if not fpath.exists():
                if f"data/{name}" in _listed_data_paths(capsule_dir):
                    # The manifest says the capsule carries this evidence; its
                    # absence is a deletion, which must fail like a swap.
                    ok = False
                    out(f"FAIL  data/{name}: sealed by {run_id} and listed in the manifest, but missing")
                else:
                    out(f"NOTE  data/{name}: sealed by {run_id} but not in this capsule")
                continue
            sealed_names.add(f"data/{name}")
            actual = "sha256:" + _sha256(fpath)
            if actual == f["digest"]:
                out(f"PASS  data/{name} matches the digest sealed by {run_id}")
            else:
                ok = False
                out(f"FAIL  data/{name} differs from the digest sealed by {run_id}")
    try:
        manifest = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        manifest = {}
    for art in manifest.get("data_artifacts") or []:
        ra = (art.get("retained_artifact") or {}).get("path")
        if art.get("binding") == "producer_sealed" and ra not in sealed_names:
            ok = False
            out(f"FAIL  {art.get('path')} claims a producer-sealed binding but no sealed record "
                f"names {ra}")
        elif art.get("path") and art.get("binding") != "producer_sealed":
            out(f"NOTE  {art['path']}: {art.get('binding', 'self_attested')} "
                f"({art.get('status')}); no sealed producer digest names this series")
        if art.get("path") and ra:
            if (capsule_dir / ra).exists() and (capsule_dir / art["path"]).exists():
                if _csv_matches_json(capsule_dir / art["path"], capsule_dir / ra):
                    out(f"PASS  {art['path']} equals the retained series {ra}")
                else:
                    ok = False
                    out(f"FAIL  {art['path']} does not equal the retained series {ra}")
    return ok


# --------------------------------------------------------------------------- #
# Live cross-check: run log vs the values retained in session.json
# --------------------------------------------------------------------------- #

def _slot_results(raw: dict) -> list:
    """Every retained slot result as ``(slot, result_dict)``.

    Real exports store slots as top-level keys shaped
    ``{feature_id: {params_key: {"data":..., "meta":...}}}`` (flag
    ``_hydro_slots_v2``). Older fixtures put ``{"data":...}`` under
    ``session["slots"][slot]``; both are read.
    """
    found = []
    legacy = raw.get("slots")
    if isinstance(legacy, dict):
        for slot, result in legacy.items():
            if isinstance(result, dict):
                found.append((slot, result))
    for slot, value in raw.items():
        if slot == "slots" or not isinstance(value, dict):
            continue
        if not (raw.get("_hydro_slots_v2") or "__legacy__" in value):
            continue
        for by_key in value.values():
            if not isinstance(by_key, dict):
                continue
            for result in by_key.values():
                if isinstance(result, dict) and isinstance(result.get("data"), dict):
                    found.append((slot, result))
    return found


def _computed_at(result: dict) -> str:
    meta = result.get("meta")
    return str(meta.get("computed_at", "")) if isinstance(meta, dict) else ""


def _candidate(entry: dict, run_id: str, results: list, is_latest_for_tool: bool):
    """The retained result a run-log row can honestly be compared with."""
    exact = [r for _, r in results
             if isinstance(r.get("meta"), dict) and r["meta"].get("run_id") == run_id]
    if exact:
        return exact[0], "run_id"
    if not is_latest_for_tool:
        return None, "superseded by a later run of the same tool"
    tool = entry.get("tool_name", "")
    same_tool = [r for _, r in results
                 if isinstance(r.get("meta"), dict) and r["meta"].get("tool") == tool]
    if not same_tool and tool in _LEGACY_TOOL_TO_SLOT:
        same_tool = [r for slot, r in results if slot == _LEGACY_TOOL_TO_SLOT[tool]]
    if not same_tool:
        return None, "no retained result for this tool"
    return max(same_tool, key=_computed_at), "latest result of the same tool"


def live_cross_check(capsule_dir: Path, tolerance: float = DEFAULT_TOLERANCE):
    """Compare numeric ``key_outputs`` with retained slot values.

    Returns ``(comparisons, skipped)``. Each comparison has run_id, key,
    expected, actual, deviation_pct, status. Nothing is recomputed.
    """
    rl_path = capsule_dir / "run_log.json"
    sj_path = capsule_dir / "session.json"
    if not rl_path.exists() or not sj_path.exists():
        return [], [("-", "run_log.json or session.json not found")]
    run_log = json.loads(rl_path.read_text(encoding="utf-8"))
    raw = json.loads(sj_path.read_text(encoding="utf-8"))
    results = _slot_results(raw)

    latest = {}
    for run_id, entry in run_log.items():
        if not isinstance(entry, dict):
            continue
        tool = entry.get("tool_name", "")
        stamp = str(entry.get("timestamp", ""))
        if tool not in latest or (stamp, run_id) > latest[tool]:
            latest[tool] = (stamp, run_id)

    comparisons, skipped = [], []
    for run_id, entry in sorted(run_log.items()):
        if not isinstance(entry, dict):
            continue
        key_outputs = entry.get("key_outputs")
        if not isinstance(key_outputs, dict) or not key_outputs:
            continue
        is_latest = latest.get(entry.get("tool_name", ""), (None, None))[1] == run_id
        result, how = _candidate(entry, run_id, results, is_latest)
        if result is None:
            skipped.append((run_id, how))
            continue
        data = result.get("data") if isinstance(result.get("data"), dict) else {}
        for key, expected in key_outputs.items():
            if key.startswith("_") or isinstance(expected, bool) or not isinstance(expected, (int, float)):
                continue
            actual = data.get(key)
            if isinstance(actual, bool) or not isinstance(actual, (int, float)):
                continue
            if not (math.isfinite(expected) and math.isfinite(actual)):
                continue
            if expected == 0:
                deviation = 0.0 if abs(actual) < 1e-9 else float("inf")
            else:
                deviation = abs(actual - expected) / abs(expected)
            comparisons.append({
                "run_id": run_id, "key": key, "expected": expected, "actual": actual,
                "deviation_pct": round(deviation * 100, 3), "matched_by": how,
                "status": "pass" if deviation <= tolerance else "fail",
            })
    return comparisons, skipped


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #

def replay_status(integrity_ok: bool, live: bool, n_comparisons: int, comparisons_ok: bool) -> str:
    """The strongest level actually reached. Never ``recomputed``."""
    if not integrity_ok:
        return "not_performed"
    if live and n_comparisons > 0 and comparisons_ok:
        return "cross_check"
    return "archive_integrity"


def run(capsule_dir: Path, live: bool = False, tolerance: float = DEFAULT_TOLERANCE, out=print) -> int:
    hashes_ok, hash_results = verify_hashes(capsule_dir, out=out)
    n_pass = sum(1 for r in hash_results if r["status"] == "pass")
    n_bad = sum(1 for r in hash_results if r["status"] != "pass")
    out(f"\nHash check: {n_pass} pass, {n_bad} fail")

    records_ok = True
    rl_path = capsule_dir / "run_log.json"
    if rl_path.exists():
        summary = verify_run_log(json.loads(rl_path.read_text(encoding="utf-8")))
        for run_id, why in summary["failures"]:
            out(f"FAIL  record {run_id}: {why}")
        records_ok = not summary["failures"]
        out(f"Run records: {summary['verified']} of {summary['v2_records']} v2 records verify; "
            f"{summary['unbound']} sealed but unbound to their row; "
            f"{summary['legacy']} legacy rows have no record; {summary['record_errors']} carry a record_error")
    else:
        out("Run records: run_log.json not found")

    bindings_ok = verify_data_bindings(capsule_dir, out=out)

    comparisons, comparisons_ok = [], True
    if live:
        comparisons, skipped = live_cross_check(capsule_dir, tolerance)
        for c in comparisons:
            if c["status"] == "pass":
                out(f"PASS  {c['run_id']}:{c['key']}  {c['expected']:.4g} ~ {c['actual']:.4g}")
            else:
                out(f"FAIL  {c['run_id']}:{c['key']}  expected={c['expected']:.4g}  "
                    f"got={c['actual']:.4g}  ({c['deviation_pct']:.1f}%)")
        comparisons_ok = all(c["status"] == "pass" for c in comparisons)
        for run_id, why in skipped:
            out(f"SKIP  {run_id}: {why}")

    integrity_ok = hashes_ok and records_ok and bindings_ok
    if not hash_results and not (rl_path.exists() and summary["v2_records"]):
        integrity_ok = False        # nothing was actually checked
        out("FAIL  archive has no files and no records; nothing was verified.")
    status = replay_status(integrity_ok, live, len(comparisons), comparisons_ok)
    out(f"\nreplay_status: {status}")
    out("recomputation: not_performed")
    if live:
        out(f"comparisons: {len(comparisons)}")

    if not (integrity_ok and comparisons_ok):
        return 1
    if live and not comparisons:
        out("FAIL  --live found no comparable values; nothing was cross-checked.")
        return 2
    return 0


def main(argv=None, capsule_dir: Path | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    tolerance = DEFAULT_TOLERANCE
    for arg in argv:
        if arg.startswith("--tolerance="):
            try:
                tolerance = float(arg.split("=", 1)[1])
            except ValueError:
                pass
    return run(capsule_dir or Path(__file__).parent, live="--live" in argv, tolerance=tolerance)


def source_text() -> str:
    """The text written to a capsule as ``replay.py`` (this file, verbatim)."""
    return Path(__file__).read_text(encoding="utf-8")



def _listed_data_paths(capsule_dir: Path) -> set:
    """data/ paths the manifest claims the capsule carries (files + data_artifacts)."""
    try:
        m = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        return set()
    listed = {e.get("path") for e in m.get("files") or [] if isinstance(e, dict)}
    for art in m.get("data_artifacts") or []:
        if isinstance(art, dict):
            listed.add(art.get("path"))
            listed.add(art.get("retained_artifact", {}).get("path") if isinstance(art.get("retained_artifact"), dict) else None)
    return {x for x in listed if isinstance(x, str) and x.startswith("data/")}

if __name__ == "__main__":
    sys.exit(main())
