#!/usr/bin/env python3
"""
AI-Hydro capsule verifier — replay.py

Generated by ai_hydro.mcp.tools_session.export_session. Standard library only;
it does not import ai_hydro.

This script checks the archive. It does NOT re-run any computation, and it
prints exactly which level it reached:

    archive_integrity  every file matches its recorded SHA-256 and every v2
                       run record verifies (record seal and the binding to its
                       run-log row). Says nothing about whether the numbers
                       would be produced again.
    cross_check        (--live, at least one comparison, all passed) numeric
                       outputs in run_log.json agree with the values retained
                       in session.json. Still no recomputation.
    not_performed      an integrity check failed; no level is established.

Partial coverage (rows or claim revisions withheld for privacy) is reported as a
"coverage:" line, not as a level. When the capsule carries records/claim_revisions.json
each claim's revision chain is verified; when it carries bundle.json the bundle,
its records and manifest-sha256.txt are verified by a stdlib mirror of
aihydro_core.export.verify_crate (which does NOT regenerate and byte-compare the
crate; if aihydro_core is importable that check is run too). Integrity is not origin.

Usage:
    python replay.py                     # archive integrity
    python replay.py --live              # also cross-check run log vs session
    python replay.py --tolerance=0.02    # allow 2% deviation (default 1%)
    python replay.py --allowed-signers FILE
                                         # verify approval signatures against
                                         # a key file YOU supply (for example
                                         # the owner's published GitHub keys)

Approvals (approvals/ in the capsule) are verified only against the signer file
you pass; the capsule carries no trust root and the exporting machine's is not
consulted. Without --allowed-signers each signed approval is reported "not
verified" and never PASS. Requires ssh-keygen (OpenSSH 8.0+) on PATH.

Exit code: 0 = all checks passed, 1 = a check failed (including any approval),
           2 = --live found no comparable values (nothing was cross-checked).
"""
from __future__ import annotations

import decimal
import hashlib
import json
import base64
import math
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

MANIFEST_FILE = "capsule_manifest.json"
DEFAULT_TOLERANCE = 0.01

# Legacy exports (and hand-built fixtures) keep slots under session["slots"].
_LEGACY_TOOL_TO_SLOT = {
    "extract_hydrological_signatures": "signatures",
    "extract_geomorphic_parameters": "geomorphic",
    "compute_twi": "twi",
    "separate_baseflow": "baseflow",
    "train_hydro_model": "model",
    "get_model_results": "model",
    "delineate_watershed": "watershed",
    "delineate_watershed_from_point": "watershed",
    "fetch_streamflow_data": "streamflow",
}


# --------------------------------------------------------------------------- #
# aihydro.c14n/1 for JSON-native values (record dicts read back from JSON):
# tagging (non-finite floats, ints beyond 2**53, "$"-keyed dicts) followed by
# RFC 8785 (JCS) serialisation. Copied from aihydro_core.records.canonical;
# tests assert it reproduces core's golden vectors and digests.
# --------------------------------------------------------------------------- #

_MAX_SAFE_INT = 2 ** 53


def _encode(value):
    if value is None or isinstance(value, (bool, str)):
        return value
    if isinstance(value, int):
        if -_MAX_SAFE_INT <= value <= _MAX_SAFE_INT:
            return value
        return {"$int": str(int(value))}
    if isinstance(value, float):
        if math.isnan(value):
            return {"$float": "nan"}
        if math.isinf(value):
            return {"$float": "inf" if value > 0 else "-inf"}
        return float(value)
    if isinstance(value, dict):
        out = {}
        for key, item in value.items():
            if isinstance(key, bool) or not isinstance(key, (str, int)):
                raise TypeError("dict key has no canonical form")
            skey = key if isinstance(key, str) else str(key)
            if skey in out:
                raise TypeError("dict keys collide after stringification")
            out[skey] = _encode(item)
        if any(k.startswith("$") for k in out):
            return {"$map": out}
        return out
    if isinstance(value, (list, tuple)):
        return [_encode(v) for v in value]
    raise TypeError("cannot encode %s" % type(value).__name__)


def _es_number(x):
    """ECMAScript Number::toString for a finite double (RFC 8785 3.2.2.3)."""
    if x == 0:
        return "0"
    if x < 0:
        return "-" + _es_number(-x)
    sign, digit_tuple, exp = decimal.Decimal(repr(x)).as_tuple()
    digits = "".join(map(str, digit_tuple)).rstrip("0") or "0"
    k = len(digits)
    n = len(digit_tuple) + exp
    if k <= n <= 21:
        return digits + "0" * (n - k)
    if 0 < n <= 21:
        return digits[:n] + "." + digits[n:]
    if -6 < n <= 0:
        return "0." + "0" * (-n) + digits
    e = n - 1
    exp_str = ("+" if e >= 0 else "-") + str(abs(e))
    if k == 1:
        return digits + "e" + exp_str
    return digits[0] + "." + digits[1:] + "e" + exp_str


_ESCAPES = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _es_string(s):
    out = ['"']
    for ch in s:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _serialize(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return _es_number(v)
    if isinstance(v, str):
        return _es_string(v)
    if isinstance(v, list):
        return "[" + ",".join(_serialize(i) for i in v) + "]"
    items = sorted(v.items(), key=lambda kv: kv[0].encode("utf-16-be", "surrogatepass"))
    return "{" + ",".join(_es_string(k) + ":" + _serialize(val) for k, val in items) + "}"


def canonical_bytes(value) -> bytes:
    return _serialize(_encode(value)).encode("utf-8")


def c14n_digest(value):
    """``sha256:<64 hex>`` of the canonical encoding (raises on unencodable input)."""
    return "sha256:" + hashlib.sha256(_serialize(_encode(value)).encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------- #
# Claim revision chains: vendored verbatim from ai_hydro/capsule/claim_chain_verify.py
# (a test pins that the functions below are source-identical to that module, and
# that both agree with aihydro_core on shared golden vectors).
# --------------------------------------------------------------------------- #

CLAIM_REVISION_SCHEMA = "aihydro.claim_revision_record/1"
CANONICALIZATION = "aihydro.c14n/1"
ACTOR_KINDS = ("human", "agent", "package", "system")
REDACTED_KEY = "redacted_for_privacy"
_KNOWN_FIELDS = (
    "schema", "canonicalization", "session_id", "claim_id", "revision", "supersedes",
    "revision_digest", "content", "cause", "actor", "recorded_at", "record_digest",
)
_HEX = "0123456789abcdef"


def is_digest(value):
    if not isinstance(value, str) or not value.startswith("sha256:"):
        return False
    hexpart = value[7:]
    return len(hexpart) == 64 and all(c in _HEX for c in hexpart)


# --------------------------------------------------------------- ClaimRevision mirror
def _valid(d):
    """The ClaimRevision constructor's checks (after ``from_dict`` fills defaults)."""
    if not d["session_id"] or not d["claim_id"]:
        return False
    revision = d["revision"]
    if isinstance(revision, bool) or not isinstance(revision, int) or revision < 0:
        return False
    if not is_digest(d["revision_digest"]):
        return False
    if d.get("record_digest") is not None and not is_digest(d["record_digest"]):
        return False
    supersedes = d.get("supersedes")
    if supersedes is not None and not is_digest(supersedes):
        return False
    if revision == 0 and supersedes is not None:
        return False
    if revision > 0 and supersedes is None:
        return False
    if not isinstance(d["content"], dict) or not isinstance(d["cause"], dict):
        return False
    cause = d["cause"]
    if not isinstance(cause.get("tool"), str) or not cause["tool"]:
        return False
    if not isinstance(cause.get("reason"), str) or not cause["reason"]:
        return False
    run_id = cause.get("run_id")
    if run_id is not None and (not isinstance(run_id, str) or not run_id):
        return False
    actor = d["actor"]
    if not isinstance(actor, dict) or actor.get("kind") not in ACTOR_KINDS or not actor.get("id"):
        return False
    return True


def verify_claim_revision(d):
    """True iff ``d`` is a valid, sealed, unmodified claim revision row.

    Mirrors ``aihydro_core.records.verify_claim_revision_dict`` (never trusts the
    declared digest; any constructor failure is False).
    """
    try:
        if not isinstance(d, dict):
            return False
        # from_dict: known fields present in d; defaults for the rest. recorded_at has
        # a clock default in core, so a row without it cannot match its digest.
        row = {k: d[k] for k in _KNOWN_FIELDS if k in d}
        if "recorded_at" not in row:
            return False
        row.setdefault("schema", CLAIM_REVISION_SCHEMA)
        row.setdefault("canonicalization", CANONICALIZATION)
        for required in ("session_id", "claim_id", "revision", "revision_digest",
                         "content", "cause", "actor"):
            if required not in row:
                return False
        if not _valid(row):
            return False
        if row.get("record_digest") is None:
            return False
        payload = {k: v for k, v in row.items() if v is not None and k != "record_digest"}
        for key, value in d.items():            # unknown fields round-trip into the digest
            if key not in _KNOWN_FIELDS:
                payload.setdefault(key, value)
        return c14n_digest(payload) == row["record_digest"]
    except Exception:
        return False


def verify_chain(rows):
    """True iff ``rows`` is one claim's complete, intact chain (mirrors core).

    Each row verifies, shares ``session_id`` and ``claim_id``, counts
    ``revision`` 0, 1, 2, ... in order, and ``supersedes`` equals the previous
    row's ``revision_digest``. An empty chain is False.
    """
    try:
        if not rows:
            return False
        first = rows[0]
        prev = None
        for i, row in enumerate(rows):
            if not verify_claim_revision(row) or row["revision"] != i:
                return False
            if row["session_id"] != first["session_id"] or row["claim_id"] != first["claim_id"]:
                return False
            if prev is not None and row.get("supersedes") != prev["revision_digest"]:
                return False
            prev = row
        return True
    except Exception:
        return False


# --------------------------------------------------------------- exported-file check
def verify_exported(doc, expected_heads=None):
    """Per-claim verdicts for a ``records/claim_revisions.json`` document.

    Returns ``{claim_id: {"status": ..., "revisions": n, "detail": str}}`` with
    status one of:

    * ``verified``: whole chain verifies (and matches ``expected_heads`` if given);
    * ``partial``: chain links hold and every non-redacted row verifies, but
      privacy-redacted stubs cannot be re-sealed from the capsule;
    * ``corrupt_at_export``: the source store failed its own check at export;
    * ``failed``: a seal, link, ordering or anchor check failed.

    ``expected_heads`` maps ``claim_id -> revision_digest`` pinned outside the
    chain; a tail that was cut or re-sealed then fails instead of verifying.
    Every row's ``session_id`` must equal the document's.
    """
    out = {}
    claims = doc.get("claims") if isinstance(doc, dict) else None
    if not isinstance(claims, dict):
        return out
    heads = expected_heads or {}
    for cid in sorted(claims):
        entry = claims[cid]
        rows = entry.get("rows") if isinstance(entry, dict) else None
        if not isinstance(entry, dict) or entry.get("status") == "corrupt":
            out[cid] = {"status": "corrupt_at_export", "revisions": 0,
                        "detail": "source store failed verification at export; rows withheld"}
            continue
        if not isinstance(rows, list) or not rows:
            out[cid] = {"status": "failed", "revisions": 0, "detail": "no rows"}
            continue
        stubs = [r for r in rows if isinstance(r, dict) and r.get(REDACTED_KEY)]
        foreign = [r.get("revision") for r in rows
                   if not isinstance(r, dict) or r.get("session_id") != doc.get("session_id")]
        if foreign:
            out[cid] = {"status": "failed", "revisions": len(rows),
                        "detail": "row session_id differs from the document's (revision(s) %s)" % foreign}
            continue
        if not stubs:
            ok = verify_chain(rows)
            detail = "chain verifies" if ok else "seal, link or ordering check failed"
        else:
            ok, detail = _verify_with_stubs(rows)
        status = "failed" if not ok else ("partial" if stubs else "verified")
        if ok and cid in heads and rows[-1].get("revision_digest") != heads[cid]:
            status, detail = "failed", "head revision does not match the pinned anchor (tail cut or re-sealed)"
        out[cid] = {"status": status, "revisions": len(rows), "detail": detail}
    return out


def _verify_with_stubs(rows):
    first = rows[0]
    prev = None
    for i, row in enumerate(rows):
        if not isinstance(row, dict) or row.get("revision") != i:
            return False, "revision numbering broken at position %d" % i
        if row.get("session_id") != first.get("session_id") or row.get("claim_id") != first.get("claim_id"):
            return False, "mixed session or claim at revision %d" % i
        if not row.get(REDACTED_KEY) and not verify_claim_revision(row):
            return False, "seal failed at revision %d" % i
        if prev is not None and row.get("supersedes") != prev.get("revision_digest"):
            return False, "link broken at revision %d" % i
        if not is_digest(row.get("revision_digest")):
            return False, "bad revision_digest at revision %d" % i
        prev = row
    return True, "links hold; redacted rows cannot be re-sealed from the capsule"


_RECORD_DEFAULTS = (
    ("schema", "aihydro.run/2"), ("canonicalization", "aihydro.c14n/1"),
    ("status", "ok"), ("input_refs", []), ("parents", []), ("extra", {}),
)


def record_seal_ok(record: dict) -> bool:
    """True iff ``record`` is sealed and unchanged (mirrors RunRecord.verify)."""
    declared = record.get("record_digest")
    if not declared:
        return False
    payload = {k: v for k, v in record.items() if k != "record_digest" and v is not None}
    for name, default in _RECORD_DEFAULTS:
        payload.setdefault(name, default)
    try:
        return c14n_digest(payload) == declared
    except Exception:
        return False


def verify_run_log(run_log: dict) -> dict:
    """Verify every v2 record in a run log. Rows without a record are legacy."""
    summary = {"rows": 0, "v2_records": 0, "verified": 0, "unbound": 0, "legacy": 0,
               "unsealable": 0, "unsealable_rows": [],
               "record_errors": 0, "redacted": 0, "failures": []}
    for run_id, entry in sorted(run_log.items()):
        summary["rows"] += 1
        if isinstance(entry, dict) and entry.get("integrity") == "seal_mismatch_at_export":
            summary["failures"].append((run_id, "row did not verify when exported (seal_mismatch_at_export)"))
            continue
        if isinstance(entry, dict) and entry.get("redacted_for_privacy"):
            # Legacy sealed row withheld on export (it held a local path): its body is
            # not verifiable here, but a carried record must still hold its seal.
            summary["redacted"] += 1
            rec = entry.get("record")
            if isinstance(rec, dict):
                if not record_seal_ok(rec) or rec.get("record_digest") != entry.get("record_digest") \
                        or rec.get("run_id") != run_id:
                    summary["failures"].append((run_id, "redacted row's record does not verify"))
            continue
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict):
            summary["legacy"] += 1
            if isinstance(entry, dict) and entry.get("record_status") == "unsealable":
                summary["unsealable"] += 1
                summary["unsealable_rows"].append((run_id, str(entry.get("record_status_reason"))))
            continue
        summary["v2_records"] += 1
        if record.get("record_error"):
            summary["record_errors"] += 1
        if record.get("run_id") != run_id:
            summary["failures"].append((run_id, "record.run_id does not match its row"))
            continue
        if not record_seal_ok(record):
            summary["failures"].append((run_id, "record_digest mismatch"))
            continue
        expected = (record.get("extra") or {}).get("entry_digest")
        if expected is None:
            summary["unbound"] += 1     # sealed but not bound to its row: not "verified"
            continue
        if expected is not None:
            body = {k: v for k, v in entry.items() if k != "record"}
            try:
                actual = c14n_digest(body)
            except Exception:
                actual = None
            if actual != expected:
                summary["failures"].append((run_id, "run-log row changed after its record was sealed"))
                continue
        summary["verified"] += 1
    return summary


# --------------------------------------------------------------------------- #
# File hashes
# --------------------------------------------------------------------------- #

def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_hashes(capsule_dir: Path, out=print):
    manifest_path = capsule_dir / MANIFEST_FILE
    if not manifest_path.exists():
        out(f"FAIL  {MANIFEST_FILE} not found")
        return False, []
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    results = []
    for entry in manifest["files"]:
        fpath = capsule_dir / entry["path"]
        if not fpath.exists():
            out(f"MISS  {entry['path']}")
            results.append({"path": entry["path"], "status": "missing"})
            continue
        actual = _sha256(fpath)
        ok = actual == entry["sha256"]
        detail = "" if ok else f"  expected={entry['sha256'][:12]}...  actual={actual[:12]}..."
        out(f"{'PASS' if ok else 'FAIL'}  {entry['path']}{detail}")
        results.append({"path": entry["path"], "status": "pass" if ok else "fail"})
    return all(r["status"] == "pass" for r in results), results


# --------------------------------------------------------------------------- #
# Served data: bind data/ files to the producer's SEALED record
# --------------------------------------------------------------------------- #

def _retained_name(path: str) -> str:
    # "session-data:<file>" / "workspace:<rel>" refs (and legacy absolute paths)
    for scheme in ("session-data:", "workspace:"):
        if path.startswith(scheme):
            path = path[len(scheme):]
            break
    return Path(path).name.split(".data.", 1)[-1]


def _csv_matches_json(csv_path: Path, json_path: Path) -> bool:
    """The derived CSV holds exactly the retained JSON's dates and q_cms."""
    try:
        body = json.loads(json_path.read_text(encoding="utf-8"))
        lines = csv_path.read_text(encoding="utf-8").splitlines()
        if lines[0].split(",") != ["date", "q_cms"]:
            return False
        rows = [ln.split(",") for ln in lines[1:]]
        dates, q = body["dates"], body["q_cms"]
        if len(rows) != len(dates):
            return False
        for (d, v), d0, v0 in zip(rows, dates, q):
            if d != str(d0) or (v == "") != (v0 is None) or (v != "" and float(v) != float(v0)):
                return False
        return True
    except Exception:
        return False


def verify_data_bindings(capsule_dir: Path, out=print) -> bool:
    """Check retained data files against digests sealed in producer records.

    Reads run_log.json (not the manifest), so a regenerated manifest cannot
    hide a swapped series. A record whose seal fails is ignored here; the
    record check reports it. Files with no sealed digest are reported as
    self-attested, never as bound.
    """
    ok = True
    rl_path = capsule_dir / "run_log.json"
    run_log = json.loads(rl_path.read_text(encoding="utf-8")) if rl_path.exists() else {}
    sealed_names = set()
    for run_id, entry in sorted(run_log.items()):
        record = entry.get("record") if isinstance(entry, dict) else None
        if not isinstance(record, dict) or not record_seal_ok(record):
            continue
        for f in (record.get("extra") or {}).get("retained_files") or []:
            if not (isinstance(f, dict) and f.get("path") and f.get("digest")):
                continue
            name = _retained_name(f["path"])
            fpath = capsule_dir / "data" / name
            if not fpath.exists():
                if f"data/{name}" in _listed_data_paths(capsule_dir):
                    # The manifest says the capsule carries this evidence; its
                    # absence is a deletion, which must fail like a swap.
                    ok = False
                    out(f"FAIL  data/{name}: sealed by {run_id} and listed in the manifest, but missing")
                else:
                    out(f"NOTE  data/{name}: sealed by {run_id} but not in this capsule")
                continue
            sealed_names.add(f"data/{name}")
            actual = "sha256:" + _sha256(fpath)
            if actual == f["digest"]:
                out(f"PASS  data/{name} matches the digest sealed by {run_id}")
            else:
                ok = False
                out(f"FAIL  data/{name} differs from the digest sealed by {run_id}")
    try:
        manifest = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        manifest = {}
    for art in manifest.get("data_artifacts") or []:
        ra = (art.get("retained_artifact") or {}).get("path")
        if art.get("binding") == "producer_sealed" and ra not in sealed_names:
            ok = False
            out(f"FAIL  {art.get('path')} claims a producer-sealed binding but no sealed record "
                f"names {ra}")
        elif art.get("path") and art.get("binding") != "producer_sealed":
            out(f"NOTE  {art['path']}: {art.get('binding', 'self_attested')} "
                f"({art.get('status')}); no sealed producer digest names this series")
        if art.get("path") and ra:
            if (capsule_dir / ra).exists() and (capsule_dir / art["path"]).exists():
                if _csv_matches_json(capsule_dir / art["path"], capsule_dir / ra):
                    out(f"PASS  {art['path']} equals the retained series {ra}")
                else:
                    ok = False
                    out(f"FAIL  {art['path']} does not equal the retained series {ra}")
    return ok


# --------------------------------------------------------------------------- #
# Approvals: verify signed human approvals against a SUPPLIED signer file
# --------------------------------------------------------------------------- #

APPROVAL_NAMESPACE = "aihydro-approval@v1"
APPROVALS_INDEX = "approvals/index.json"


def _sshsig_key(armored: str):
    """``(key_type, fingerprint, namespace)`` from an armored SSHSIG, or None."""
    try:
        lines = [ln.strip() for ln in armored.strip().splitlines()]
        if lines[0] != "-----BEGIN SSH SIGNATURE-----" or lines[-1] != "-----END SSH SIGNATURE-----":
            return None
        blob = base64.b64decode("".join(lines[1:-1]), validate=True)
        if blob[:6] != b"SSHSIG":
            return None

        def read(buf, off):
            (n,) = struct.unpack_from(">I", buf, off)
            return buf[off + 4: off + 4 + n], off + 4 + n

        pub, off = read(blob, 10)
        ns, _ = read(blob, off)
        ktype, _ = read(pub, 0)
        fp = "SHA256:" + base64.b64encode(hashlib.sha256(pub).digest()).decode().rstrip("=")
        return ktype.decode("ascii"), fp, ns.decode("utf-8")
    except Exception:
        return None


def _ssh_verify(record: dict, signers: Path):
    """``(ok, reason)`` from ``ssh-keygen -Y verify`` over the sealed digest."""
    exe = shutil.which("ssh-keygen")
    if exe is None:
        return False, "ssh-keygen not found on PATH"
    principal = (record.get("approver") or {}).get("id")
    if not principal:
        return False, "approval has no approver id"
    with tempfile.TemporaryDirectory(prefix="aihydro-replay-") as tmp:
        sig = Path(tmp) / "approval.sig"
        sig.write_text(record["signature"]["armored"].strip() + "\n", encoding="utf-8")
        try:
            res = subprocess.run(
                [exe, "-Y", "verify", "-f", str(signers), "-I", principal,
                 "-n", APPROVAL_NAMESPACE, "-s", str(sig)],
                input=record["record_digest"].encode("utf-8"), capture_output=True, timeout=30)
        except (OSError, subprocess.SubprocessError) as exc:
            return False, f"ssh-keygen failed: {exc}"
    if res.returncode == 0:
        return True, "signature verifies"
    msg = (res.stderr or res.stdout).decode("utf-8", "replace").strip().splitlines()
    return False, f"signature not accepted for principal {principal!r}: {msg[0] if msg else 'verify failed'}"


_APPROVAL_FILE_RE = re.compile(r"^approvals/([0-9a-f]{64})\.json$")
REVISION_SCHEMA = "aihydro.claim_revision/2"


# Mirrors ``registry.evidence`` (a test pins that they agree): v2 hashes the whole
# run row; v3 hashes the row body only, excluding the seal (``record``) and every
# ``record_status*`` key, so sealing or marking a row later does not change it.
_RUN_ROW_SEAL_KEY = "record"
_RUN_ROW_STATUS_PREFIX = "record_status"
_MAX_BRANCHING_SOURCES = 10     # versions are tried per source only up to 2**10 combinations


def _is_run_row_metadata_key(key) -> bool:
    return key == _RUN_ROW_SEAL_KEY or (isinstance(key, str) and key.startswith(_RUN_ROW_STATUS_PREFIX))


def _run_fingerprint(record: dict, version: str = "sha256-v3") -> str:
    """``registry.evidence.evidence_fingerprint`` for a run row, in ``version``."""
    if version == "sha256-v3":
        record = {k: v for k, v in record.items() if not _is_run_row_metadata_key(k)}
    elif version != "sha256-v2":
        raise ValueError(version)
    payload = json.dumps(record, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return f"{version}:" + hashlib.sha256(payload.encode()).hexdigest()


def recompute_claim_revision(session_raw: dict, run_log: dict, claim_id: str, expected: str | None = None):
    """``(claim_revision_digest, None)`` recomputed from the capsule, or ``(None, reason)``.

    Mirrors ``ai_hydro.approval.records.claim_revision_fields`` for claims whose
    evidence spans are all run-backed (the retained run row is in ``run_log.json``).
    The capsule does not carry which fingerprint version each source was bound
    in, nor whether it was sealed when the claim was bound (``evidence_seals``,
    present only for sources whose row carried a record at bind time). When
    ``expected`` is given every per-source (fingerprint version, seal bound or
    not) choice is tried, branching only on sources whose variants differ, and
    ``expected`` is returned on a match; otherwise the all-v3, seals-bound digest
    is returned. A row whose seal was deleted offers no seal-bound variant, so a
    claim bound to the sealed row matches no combination.
    Anything not reproducible in stdlib returns a precise reason, never a digest:
    dataset and paper spans (they need the raw slot / the passage index), legacy
    ``evidence`` lists, claims that are not valid scientific claims.
    """
    claims = session_raw.get("claims")
    claim = claims.get(claim_id) if isinstance(claims, dict) else None
    if not isinstance(claim, dict):
        return None, f"claim {claim_id!r} is not in session.json"
    if claim.get("evidence") and "evidence_spans" not in claim:
        return None, "claim uses the legacy 'evidence' list; its revision is not reproducible in stdlib"
    scope = claim.get("scope")
    rationale = claim.get("confidence_rationale")
    if (not isinstance(scope, dict) or not isinstance(scope.get("basins"), list)
            or not isinstance(scope.get("period"), str) or not isinstance(claim.get("claim"), str)
            or not all(isinstance(claim.get(k), str) for k in ("claim_type", "status", "confidence"))
            or not isinstance(rationale, str) or len(rationale.strip()) < 20):
        return None, "claim in session.json is not a valid scientific claim"
    spans = claim.get("evidence_spans") or []
    session_id = session_raw.get("session_id")
    norm_spans, versions, row_seals = [], {}, {}
    for span in spans:
        if not isinstance(span, dict) or not span.get("source_type") or not span.get("source_id"):
            return None, "claim has a malformed evidence span"
        kind, sid = span["source_type"], span["source_id"]
        if kind != "run":
            return None, (f"evidence span {sid!r} is a {kind} span; its fingerprint needs "
                          f"{'the raw session slot' if kind == 'dataset' else 'the passage index'}, "
                          "not reproducible in stdlib from the capsule")
        row = run_log.get(sid) if isinstance(run_log, dict) else None
        if isinstance(row, dict) and row.get("redacted_for_privacy"):
            return None, f"run {sid!r} is redacted for privacy (not verifiable from capsule)"
        if not isinstance(row, dict) or not row:
            return None, f"run {sid!r} cited by the claim is not retained in run_log.json"
        if row.get("session_id", session_id) != session_id or row.get("run_id", sid) != sid:
            return None, f"run {sid!r} has conflicting session/run identity"
        versions[sid] = {v: _run_fingerprint(row, v) for v in ("sha256-v3", "sha256-v2")}
        rec = row.get("record")
        if isinstance(rec, dict) and isinstance(rec.get("record_digest"), str) and rec["record_digest"]:
            row_seals[sid] = rec["record_digest"]
        norm_spans.append({"source_type": kind, "source_id": sid, "metric_ref": span.get("metric_ref"),
                           "page": span.get("page"), "passage_hash": span.get("passage_hash")})
    out_scope = {"basins": list(scope["basins"]), "period": scope["period"],
                 "forcing": scope.get("forcing"), "metric": scope.get("metric"),
                 "model_versions": scope.get("model_versions") or {}}
    if scope.get("basin_refs") is not None:     # same omission-when-None rule as ClaimScope (slice 3)
        out_scope["basin_refs"] = [dict(e) for e in scope["basin_refs"]]
    def _fields(chosen: dict, seals: dict | None = None) -> dict:
        fields = {
            "schema": REVISION_SCHEMA,
            "text": claim["claim"],
            "claim_type": claim["claim_type"],
            "status": claim["status"],
            "confidence": claim["confidence"],
            "confidence_rationale": rationale,
            "scope": out_scope,
            "evidence_spans": norm_spans,
            "evidence_versions": chosen,
            "limitations": list(claim.get("limitations") or []),
            "prereg_id": claim.get("prereg_id"),
            "uncertainty_verified": bool(claim.get("uncertainty_verified")),
        }
        if seals:           # omitted when empty, as in claim_revision_fields
            fields["evidence_seals"] = dict(seals)
        return fields

    def _options(sid: str) -> list:
        """Distinct ``(fingerprint, seal-or-None)`` choices for one source, default first."""
        out = []
        for seal in ((row_seals[sid], None) if sid in row_seals else (None,)):
            for ver in ("sha256-v3", "sha256-v2"):
                option = (versions[sid][ver], seal)
                if option not in out:
                    out.append(option)
        return out
    try:
        options = {s: _options(s) for s in versions}
        default = c14n_digest(_fields({s: o[0][0] for s, o in options.items()},
                                      {s: o[0][1] for s, o in options.items() if o[0][1]}))
        if expected is None or default == expected:
            return default, None
        branching = [s for s, o in options.items() if len(o) > 1]
        total = 1
        for s in branching:
            total *= len(options[s])
        if not branching or len(branching) > _MAX_BRANCHING_SOURCES or total > 2 ** _MAX_BRANCHING_SOURCES:
            return default, None
        import itertools
        for combo in itertools.product(*(options[s] for s in branching)):
            choice = {s: o[0][0] for s, o in options.items()}
            seals = {s: o[0][1] for s, o in options.items() if o[0][1]}
            for s, (fp, seal) in zip(branching, combo):
                choice[s] = fp
                seals.pop(s, None)
                if seal:
                    seals[s] = seal
            candidate = c14n_digest(_fields(choice, seals))
            if candidate == expected:
                return candidate, None
        return default, None
    except Exception as exc:
        return None, f"claim revision could not be encoded: {exc}"


def _approval_path(capsule_dir: Path, rel, digest):
    """The approval file iff ``rel`` is exactly ``approvals/<hex>.json`` for ``digest`` and a real file inside the capsule."""
    m = _APPROVAL_FILE_RE.match(rel) if isinstance(rel, str) else None
    if m is None or digest != "sha256:" + m.group(1):
        return None
    d, f = capsule_dir / "approvals", capsule_dir / rel
    if d.is_symlink() or f.is_symlink() or not f.is_file():
        return None
    return f if f.resolve().parent == d.resolve() else None


def verify_approvals(capsule_dir: Path, allowed_signers=None, out=print) -> dict:
    """Check every approval the capsule carries.

    Per approval: the sealed body digest, the binding of ``claim_revision_digest``
    to the registry stamp, and (v2 with ``allowed_signers``) the SSHSIG under the
    supplied file, namespace ``aihydro-approval@v1`` and principal = approver id.
    Without a signer file a signed approval is "not verified", never PASS.
    Returns counts; ``failed > 0`` means exit 1.
    """
    c = {"verified": 0, "failed": 0, "unsigned": 0, "unverified": 0, "no_approval": 0, "claims": 0}
    index_path = capsule_dir / APPROVALS_INDEX
    if not index_path.exists():
        out("Approvals: none in this capsule (no promoted claims were exported)")
        return c
    try:
        index = json.loads(index_path.read_text(encoding="utf-8"))
        claims = index["claims"]
    except Exception:
        out(f"FAIL  {APPROVALS_INDEX} is unreadable")
        c["failed"] += 1
        return c
    try:
        session_raw = json.loads((capsule_dir / "session.json").read_text(encoding="utf-8"))
        session_raw = session_raw if isinstance(session_raw, dict) else {}
    except Exception:
        session_raw = {}
    try:
        run_log = json.loads((capsule_dir / "run_log.json").read_text(encoding="utf-8"))
    except Exception:
        run_log = {}
    signers = Path(allowed_signers) if allowed_signers else None
    if signers is not None and not signers.is_file():
        out(f"FAIL  --allowed-signers file not found: {signers}")
        c["failed"] += 1
        signers = None
    for e in claims:
        c["claims"] += 1
        label = f"{e.get('claim_id')} ({e.get('registry_id') or 'no registry id'})"
        status = e.get("status")
        if status == "no_approval":
            c["no_approval"] += 1
            out(f"NOTE  approval {label}: no approval record ({e.get('reason', 'self_asserted')}); not approved")
            continue
        if status != "record_carried":
            c["failed"] += 1
            out(f"FAIL  approval {label}: {e.get('reason') or status}")
            continue
        path = _approval_path(capsule_dir, e.get("approval_file"), e.get("record_digest"))
        if path is None:
            c["failed"] += 1
            out(f"FAIL  approval {label}: approval file must be approvals/<64 hex>.json named by its "
                f"record digest, a regular file inside the capsule (got {e.get('approval_file')!r})")
            continue
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            c["failed"] += 1
            out(f"FAIL  approval {label}: record file {e.get('approval_file')} unreadable")
            continue
        v2 = record.get("schema") == "aihydro.approval/2"
        skip = {"record_digest", "signature"} if v2 else {"record_digest"}
        try:
            sealed = c14n_digest({k: v for k, v in record.items() if k not in skip}) == record.get("record_digest")
        except Exception:
            sealed = False
        stamp = (e.get("registry_stamp") or {})
        problems = []
        if not sealed:
            problems.append("sealed body digest mismatch (record altered)")
        if record.get("record_digest") != e.get("record_digest") \
                or record.get("record_digest") != (stamp.get("approval") or {}).get("record_digest"):
            problems.append("record_digest differs from the registry stamp's")
        if not stamp.get("claim_revision_digest") \
                or record.get("claim_revision_digest") != stamp.get("claim_revision_digest"):
            problems.append("claim_revision_digest differs from the registry stamp's")
        if record.get("claim_id") != e.get("claim_id"):
            problems.append(f"the record approves claim {record.get('claim_id')!r}, not "
                            f"{e.get('claim_id')!r}")
        sess_ids = {record.get("session_id"), index.get("session_id"), session_raw.get("session_id")}
        if len(sess_ids) != 1 or None in sess_ids:
            problems.append("session id differs between the approval record "
                            f"({record.get('session_id')!r}), the approvals index "
                            f"({index.get('session_id')!r}) and session.json ({session_raw.get('session_id')!r})")
        approver = record.get("approver")
        if not isinstance(approver, dict) or approver.get("kind") != "human" or not approver.get("id"):
            problems.append("approver is not a human actor")
        if not problems:
            recomputed, why = recompute_claim_revision(session_raw, run_log, record["claim_id"],
                                                         record["claim_revision_digest"])
            if recomputed is None:
                problems.append(f"claim revision cannot be re-derived from the capsule: {why}")
            elif recomputed != record["claim_revision_digest"]:
                problems.append("the claim (or the run rows it cites) in this capsule is not the revision "
                                "the approval signed: recomputed claim_revision_digest differs")
        if problems:
            c["failed"] += 1
            out(f"FAIL  approval {label}: " + "; ".join(problems))
            continue
        if not v2:
            c["unsigned"] += 1
            out(f"UNSIGNED  approval {label}: v1 record (cli_same_user); sealed and bound to its "
                f"claim revision, but no signature exists to verify")
            continue
        sig = record.get("signature") or {}
        parsed = _sshsig_key(sig.get("armored", "")) if isinstance(sig.get("armored"), str) else None
        signer = record.get("signer") or {}
        if sig.get("namespace") != APPROVAL_NAMESPACE or parsed is None or parsed[2] != APPROVAL_NAMESPACE:
            c["failed"] += 1
            out(f"FAIL  approval {label}: missing or malformed signature (namespace {APPROVAL_NAMESPACE})")
            continue
        if parsed[1] != signer.get("fingerprint") or parsed[0] != signer.get("key_type"):
            c["failed"] += 1
            out(f"FAIL  approval {label}: signature key does not match the sealed signer")
            continue
        if signers is None:
            c["unverified"] += 1
            if allowed_signers:
                continue
            out(f"NOTE  approval {label}: not verified (no signer file supplied); "
                f"signer {signer.get('fingerprint')}")
            continue
        ok, why = _ssh_verify(record, signers)
        if ok:
            c["verified"] += 1
            out(f"PASS  approval {label}: {why}; approver {record['approver']['id']}, "
                f"signer {signer.get('fingerprint')}")
        else:
            c["failed"] += 1
            out(f"FAIL  approval {label}: {why}")
    if allowed_signers:
        out(f"approvals: {c['verified']} verified against supplied signers, {c['failed']} failed, "
            f"{c['unsigned']} unsigned (cli_same_user/opt-out)")
    else:
        out(f"approvals: {c['unverified']} not verified (no signer file supplied), {c['failed']} failed, "
            f"{c['unsigned']} unsigned (cli_same_user/opt-out)")
    if c["no_approval"]:
        out(f"claims without an approval record: {c['no_approval']}")
    return c


# --------------------------------------------------------------------------- #
# Live cross-check: run log vs the values retained in session.json
# --------------------------------------------------------------------------- #

def _slot_results(raw: dict) -> list:
    """Every retained slot result as ``(slot, result_dict)``.

    Real exports store slots as top-level keys shaped
    ``{feature_id: {params_key: {"data":..., "meta":...}}}`` (flag
    ``_hydro_slots_v2``). Older fixtures put ``{"data":...}`` under
    ``session["slots"][slot]``; both are read.
    """
    found = []
    legacy = raw.get("slots")
    if isinstance(legacy, dict):
        for slot, result in legacy.items():
            if isinstance(result, dict):
                found.append((slot, result))
    for slot, value in raw.items():
        if slot == "slots" or not isinstance(value, dict):
            continue
        if not (raw.get("_hydro_slots_v2") or "__legacy__" in value):
            continue
        for by_key in value.values():
            if not isinstance(by_key, dict):
                continue
            for result in by_key.values():
                if isinstance(result, dict) and isinstance(result.get("data"), dict):
                    found.append((slot, result))
    return found


def _computed_at(result: dict) -> str:
    meta = result.get("meta")
    return str(meta.get("computed_at", "")) if isinstance(meta, dict) else ""


def _candidate(entry: dict, run_id: str, results: list, is_latest_for_tool: bool):
    """The retained result a run-log row can honestly be compared with."""
    exact = [r for _, r in results
             if isinstance(r.get("meta"), dict) and r["meta"].get("run_id") == run_id]
    if exact:
        return exact[0], "run_id"
    if not is_latest_for_tool:
        return None, "superseded by a later run of the same tool"
    tool = entry.get("tool_name", "")
    same_tool = [r for _, r in results
                 if isinstance(r.get("meta"), dict) and r["meta"].get("tool") == tool]
    if not same_tool and tool in _LEGACY_TOOL_TO_SLOT:
        same_tool = [r for slot, r in results if slot == _LEGACY_TOOL_TO_SLOT[tool]]
    if not same_tool:
        return None, "no retained result for this tool"
    return max(same_tool, key=_computed_at), "latest result of the same tool"


def live_cross_check(capsule_dir: Path, tolerance: float = DEFAULT_TOLERANCE):
    """Compare numeric ``key_outputs`` with retained slot values.

    Returns ``(comparisons, skipped)``. Each comparison has run_id, key,
    expected, actual, deviation_pct, status. Nothing is recomputed.
    """
    rl_path = capsule_dir / "run_log.json"
    sj_path = capsule_dir / "session.json"
    if not rl_path.exists() or not sj_path.exists():
        return [], [("-", "run_log.json or session.json not found")]
    run_log = json.loads(rl_path.read_text(encoding="utf-8"))
    raw = json.loads(sj_path.read_text(encoding="utf-8"))
    results = _slot_results(raw)

    latest = {}
    for run_id, entry in run_log.items():
        if not isinstance(entry, dict):
            continue
        tool = entry.get("tool_name", "")
        stamp = str(entry.get("timestamp", ""))
        if tool not in latest or (stamp, run_id) > latest[tool]:
            latest[tool] = (stamp, run_id)

    comparisons, skipped = [], []
    for run_id, entry in sorted(run_log.items()):
        if not isinstance(entry, dict):
            continue
        key_outputs = entry.get("key_outputs")
        if not isinstance(key_outputs, dict) or not key_outputs:
            continue
        is_latest = latest.get(entry.get("tool_name", ""), (None, None))[1] == run_id
        result, how = _candidate(entry, run_id, results, is_latest)
        if result is None:
            skipped.append((run_id, how))
            continue
        data = result.get("data") if isinstance(result.get("data"), dict) else {}
        for key, expected in key_outputs.items():
            if key.startswith("_") or isinstance(expected, bool) or not isinstance(expected, (int, float)):
                continue
            actual = data.get(key)
            if isinstance(actual, bool) or not isinstance(actual, (int, float)):
                continue
            if not (math.isfinite(expected) and math.isfinite(actual)):
                continue
            if expected == 0:
                deviation = 0.0 if abs(actual) < 1e-9 else float("inf")
            else:
                deviation = abs(actual - expected) / abs(expected)
            comparisons.append({
                "run_id": run_id, "key": key, "expected": expected, "actual": actual,
                "deviation_pct": round(deviation * 100, 3), "matched_by": how,
                "status": "pass" if deviation <= tolerance else "fail",
            })
    return comparisons, skipped


# --------------------------------------------------------------------------- #
# Bundle and crate: stdlib mirror of aihydro_core.export.verify_crate
# --------------------------------------------------------------------------- #
#
# What this checks (rule ids match aihydro_core.export.rocrate_verify):
#   VER-BUNDLE-IDENTITY / VER-BUNDLE-SEAL  bundle.json names {schema, session_id,
#       objects, records}, is in canonical order, and its seal holds;
#   VER-FILE-DIGEST        every bundle object's bytes equal its sealed digest/size;
#   VER-OBJECTS-MANIFEST   bundle.objects equals capsule_manifest.json files plus the
#       manifest itself and replay.py; VER-UNLISTED-FILE any other file or a symlink;
#   VER-ASSESSOR / VER-REPLAY-MANIFEST  the verifier the bundle names is a capsule file and
#       the bundle's replay level is anchored to the on-disk manifest and to what was checked;
#   VER-SESSION            every run and claim record names the bundle's session_id (the
#       mirror only; core does not yet compare them);
#   VER-RUN-ROWS           sealed <= run entries <= sealed + withheld_for_privacy;
#   VER-GATES              declared gates equal those derived from verified, sealed-bound bodies;
#   VER-RECORD-SEAL / VER-RECORD-DIGEST / VER-BINDING / VER-CHAIN
#       run record seals, claim revision seals, basin ids from their anchors,
#       content digests, aihydro.entry/1 body bindings (and the sealed
#       extra.entry_digest), and per-claim revision chains;
#   VER-UNVERIFIABLE       a record declared unverifiable must be a privacy-withheld stub
#       (redacted_for_privacy); any other defect (seal, foreign session, missing body) fails;
#   VER-COVERAGE           the unverifiable set equals the bundle's declared one;
#   VER-BAGIT              manifest-sha256.txt covers every file and each digest holds.
# What it does NOT check: it does not regenerate ro-crate-metadata.json and
# byte-compare it (that needs the projection code, which lives in aihydro_core),
# so a crate edited consistently with nothing else is not caught here; the BagIt
# manifest only shows the crate is the file that was shipped. It does not run
# the constructor validation of every bundle field (types of optional fields,
# SPDX strings, gate codes) and not core's structural/honesty validator
# (VER-VALIDATE). When aihydro_core.export is importable, replay.py also runs its
# verify_crate and reports every rule, including VER-CRATE-REGEN and VER-VALIDATE.

_CRATE_FILE = "ro-crate-metadata.json"
_BAGIT_FILE = "manifest-sha256.txt"
_BUNDLE_FILE = "bundle.json"
_BUNDLE_SCHEMA = "aihydro.bundle/1"
_ENTRY_BINDING = "aihydro.entry/1"
_UNSEALED_KINDS = ("claim_view",)
_ANCHOR_KINDS = ("gauge_index", "network_element", "grid_cell")
_BASIN_ANCHOR_SCHEMA = "aihydro.basin_anchor/1"
_BASIN_ID_PREFIX = "aihydro:basin:"
_GATE_CODES = ("APPROVAL_REQUIRED",)
_LEVELS = ("not_performed", "archive_integrity", "cross_check", "recomputed", "independently_reproduced")


def entry_digest(obj) -> str:
    """``aihydro.entry/1``: the c14n digest of ``obj`` minus its top-level ``record``."""
    return c14n_digest({k: v for k, v in obj.items() if k != "record"})


def _unescape_token(token):
    out, i = [], 0
    while i < len(token):
        ch = token[i]
        if ch == "~":
            nxt = token[i + 1] if i + 1 < len(token) else ""
            if nxt not in ("0", "1"):
                raise ValueError("bad JSON Pointer escape")
            out.append("~" if nxt == "0" else "/")
            i += 2
        else:
            out.append(ch)
            i += 1
    return "".join(out)


def split_location(location):
    """``(file, tokens)`` for ``'<file>#<RFC 6901 pointer>'``; ValueError when malformed."""
    if not isinstance(location, str) or "#" not in location:
        raise ValueError("location must be '<file>#<pointer>'")
    path, _, pointer = location.partition("#")
    if (not path or path.startswith("/") or "\\" in path or "\x00" in path
            or any(seg in ("", ".", "..") for seg in path.split("/"))):
        raise ValueError("bad location file part")
    if pointer == "":
        return path, []
    if not pointer.startswith("/"):
        raise ValueError("JSON Pointer must be empty or start with '/'")
    return path, [_unescape_token(t) for t in pointer[1:].split("/")]


def resolve_tokens(doc, tokens):
    cur = doc
    for tok in tokens:
        if isinstance(cur, dict):
            if tok not in cur:
                raise ValueError("pointer token not found")
            cur = cur[tok]
        elif isinstance(cur, list):
            if not tok.isdigit() or (len(tok) > 1 and tok[0] == "0") or int(tok) >= len(cur):
                raise ValueError("bad array index")
            cur = cur[int(tok)]
        else:
            raise ValueError("cannot descend into a scalar")
    return cur


def scan_files(capsule_dir: Path) -> dict:
    """Every regular, non-symlink file except the crate and the BagIt manifest."""
    out = {}
    for p in sorted(capsule_dir.rglob("*")):
        if not p.is_file() or p.is_symlink():
            continue
        rel = p.relative_to(capsule_dir).as_posix()
        if rel in (_CRATE_FILE, _BAGIT_FILE):
            continue
        data = p.read_bytes()
        out[rel] = {"sha256": hashlib.sha256(data).hexdigest(), "size": len(data)}
    return out


def find_symlinks(capsule_dir: Path) -> list:
    found = []
    for dirpath, dirnames, filenames in os.walk(capsule_dir, followlinks=False):
        for name in list(dirnames) + list(filenames):
            full = Path(dirpath) / name
            if full.is_symlink():
                found.append(full.relative_to(capsule_dir).as_posix())
    return sorted(found)


def find_irregular(capsule_dir: Path) -> list:
    """Entries that are neither a regular file, a directory nor a symlink (FIFO, socket, device)."""
    found = []
    for dirpath, dirnames, filenames in os.walk(capsule_dir, followlinks=False):
        for name in filenames:
            full = Path(dirpath) / name
            if not full.is_symlink() and not full.is_file():
                found.append(full.relative_to(capsule_dir).as_posix())
    return sorted(found)


def _basin_ref_ok(rec, eid) -> bool:
    try:
        anchor = rec["anchor"]
        if not isinstance(anchor, dict) or set(anchor) != {"kind", "network", "network_version", "element"}:
            return False
        if anchor["kind"] not in _ANCHOR_KINDS or not all(
                isinstance(anchor[k], str) and anchor[k] for k in ("network", "network_version", "element")):
            return False
        expected = _BASIN_ID_PREFIX + c14n_digest({"schema": _BASIN_ANCHOR_SCHEMA, **anchor})
        return rec.get("schema") == "aihydro.basin_ref/1" and rec.get("id") == expected == eid
    except Exception:
        return False


def verify_bundle(capsule_dir: Path) -> dict | None:
    """Verify ``bundle.json`` and what it points at. ``None`` when there is no bundle.

    Returns ``{ok, failures: [(rule, entity, message)], notes, unverifiable_ids,
    records_verified, records_total, coverage, replay, claim_heads}``.
    """
    bpath = capsule_dir / _BUNDLE_FILE
    if not bpath.exists():
        return None
    res = {"ok": True, "failures": [], "notes": [], "unverifiable_ids": [], "records_verified": 0,
           "records_total": 0, "coverage": None, "replay": None, "claim_heads": {}}

    def fail(rule, message, entity=None):
        res["failures"].append((rule, entity, message))
        res["ok"] = False

    try:
        bundle = json.loads(bpath.read_text(encoding="utf-8"))
        assert isinstance(bundle, dict) and bundle.get("schema") == _BUNDLE_SCHEMA
        objects, records = bundle["objects"], bundle["records"]
        assert isinstance(objects, list) and isinstance(records, list)
        assert isinstance(bundle.get("session_id"), str) and bundle["session_id"]
        assert all(isinstance(o, dict) and isinstance(o.get("ref"), str) for o in objects)
        assert all(isinstance(r, dict) and isinstance(r.get("kind"), str) and isinstance(r.get("id"), str)
                   for r in records)
    except Exception as exc:
        fail("VER-BUNDLE-SEAL", f"cannot read a valid {_BUNDLE_FILE}: {type(exc).__name__}")
        return res
    res["coverage"], res["replay"] = bundle.get("coverage"), bundle.get("replay")
    res["claim_heads"] = bundle.get("claim_heads") if isinstance(bundle.get("claim_heads"), dict) else {}

    ordered = (objects == sorted(objects, key=lambda o: o["ref"])
               and records == sorted(records, key=lambda r: (r["kind"], r["id"])))
    try:
        ident = c14n_digest({"schema": bundle["schema"], "session_id": bundle["session_id"],
                             "objects": objects, "records": records})
        identity_ok = ordered and bundle.get("bundle_id") == ident
    except Exception:
        identity_ok = False
    if not identity_ok:
        fail("VER-BUNDLE-IDENTITY",
             "bundle_id does not name {schema, session_id, objects, records} (or order is not canonical)")
    try:
        payload = {k: v for k, v in bundle.items() if k != "record_digest" and v is not None}
        payload.setdefault("canonicalization", CANONICALIZATION)
        seal_ok = bundle.get("record_digest") is not None and c14n_digest(payload) == bundle["record_digest"]
    except Exception:
        seal_ok = False
    if not seal_ok:
        fail("VER-BUNDLE-SEAL", "bundle record_digest does not match its content")

    for link in find_symlinks(capsule_dir):
        fail("VER-UNLISTED-FILE", "symlinks are never part of a capsule", link)
    for odd in find_irregular(capsule_dir):
        fail("VER-UNLISTED-FILE", "non-regular entries (FIFO, socket, device) are never part of a capsule", odd)
    files = scan_files(capsule_dir)
    by_ref = {o["ref"]: o for o in objects}
    for path in sorted(set(files) - set(by_ref) - {_BUNDLE_FILE}):
        fail("VER-UNLISTED-FILE", "file is in the capsule but is not a bundle object (remove it, or re-export)", path)
    for ref, o in sorted(by_ref.items()):
        f = files.get(ref)
        if f is None:
            fail("VER-FILE-DIGEST", "bundle object is missing from the capsule", ref)
        elif "sha256:" + f["sha256"] != o.get("digest") or f["size"] != o.get("size"):
            fail("VER-FILE-DIGEST", "file bytes differ from the digest/size the bundle sealed", ref)
    mpath = capsule_dir / MANIFEST_FILE
    manifest = None
    if mpath.is_file():
        try:
            manifest = json.loads(mpath.read_text(encoding="utf-8"))
            listed = {m["path"]: ("sha256:" + m["sha256"], m["size"]) for m in manifest["files"]}
        except Exception as exc:
            manifest = None
            fail("VER-OBJECTS-MANIFEST", f"cannot read files from {MANIFEST_FILE}: {type(exc).__name__}")
        else:
            mine = {r: (o.get("digest"), o.get("size")) for r, o in by_ref.items()}
            for path in sorted(set(listed) | set(mine)):
                if path in (MANIFEST_FILE, "replay.py"):
                    continue
                if listed.get(path) != mine.get(path):
                    fail("VER-OBJECTS-MANIFEST", "bundle.objects and the manifest files disagree", path)
            for path in (MANIFEST_FILE, "replay.py"):
                if path not in by_ref:
                    fail("VER-OBJECTS-MANIFEST", f"{path} must be a bundle object", path)
    else:
        fail("VER-OBJECTS-MANIFEST", f"{MANIFEST_FILE} is missing")
    rp = bundle.get("replay") if isinstance(bundle.get("replay"), dict) else {}
    assessor = rp.get("assessor") if isinstance(rp.get("assessor"), dict) else None
    if assessor is not None:
        named = assessor.get("url") if assessor.get("url") in files else "replay.py"
        if not assessor.get("sha256"):
            fail("VER-ASSESSOR", f"replay.assessor must carry the sha256 of {named}")
        elif named not in files:
            fail("VER-ASSESSOR", f"the verifier file {named} is not in the capsule", named)
        elif files[named]["sha256"] != assessor["sha256"]:
            fail("VER-ASSESSOR", f"replay.assessor.sha256 is not the digest of the file it names ({named})", named)
    try:
        rank = _LEVELS.index(rp["status"])
        if rank > _LEVELS.index(rp["checked_status"]) or rank > _LEVELS.index(rp["manifest_status"]):
            fail("VER-REPLAY-MANIFEST", "replay.status exceeds replay.manifest_status or replay.checked_status")
        if manifest is not None:
            m_raw = manifest.get("replay_status")
            m_level, m_complete = ("archive_integrity", False) if m_raw == "archive_integrity_partial" else (m_raw, True)
            if rp["manifest_status"] != m_level:
                fail("VER-REPLAY-MANIFEST", f"replay.manifest_status {rp['manifest_status']!r} differs from "
                                            f"the manifest's {m_level!r}")
            if rank > _LEVELS.index(m_level):
                fail("VER-REPLAY-MANIFEST", "replay.status exceeds the level the on-disk manifest states")
            cv = bundle.get("coverage") if isinstance(bundle.get("coverage"), dict) else {}
            if not m_complete and cv.get("records_verified") == cv.get("records_total"):
                fail("VER-REPLAY-MANIFEST", "the manifest states a partial result but the bundle claims "
                                            "complete coverage")
    except (KeyError, ValueError, TypeError):
        fail("VER-REPLAY-MANIFEST", "cannot establish the replay level")

    docs = {}

    def locate(loc):
        try:
            path, tokens = split_location(loc)
        except ValueError as exc:
            return False, None, str(exc)
        if path not in by_ref:
            return False, None, f"location file {path!r} is not a sealed bundle object"
        if path not in docs:
            try:
                docs[path] = json.loads((capsule_dir / path).read_text(encoding="utf-8"))
            except (OSError, ValueError):
                docs[path] = None
        if docs[path] is None:
            return False, None, f"location file {path!r} is unreadable"
        try:
            return True, resolve_tokens(docs[path], tokens), ""
        except ValueError as exc:
            return False, None, str(exc)

    def binding_ok(body, binding):
        if not isinstance(body, dict) or not isinstance(binding, dict) or binding.get("scheme") != _ENTRY_BINDING:
            return False
        try:
            return entry_digest(body) == binding.get("digest")
        except Exception:
            return False

    not_ok = {}
    revisions = {}
    content_checks = []
    stub_runs = set()          # run rows withheld for privacy (the only acceptable partiality)
    stub_claims = set()        # claims with a privacy-withheld revision row
    for e in records:
        kind, eid = e["kind"], e["id"]
        key = (kind, eid)
        label = f"{kind}:{eid}"
        body = None
        if e.get("body_location"):
            okb, body, why = locate(e["body_location"])
            if not okb:
                if kind in _UNSEALED_KINDS:
                    fail("VER-BINDING", f"body unresolvable: {why}", label)
                else:
                    not_ok[key] = ("VER-BINDING", f"body unresolvable: {why}")
                continue
        if kind == "run" and isinstance(body, dict) and body.get("redacted_for_privacy") is True:
            stub_runs.add(eid)
        if e.get("binding") is not None and not binding_ok(body, e["binding"]):
            if kind in _UNSEALED_KINDS:
                fail("VER-BINDING", "body does not match its aihydro.entry/1 binding", label)
            else:
                not_ok[key] = ("VER-BINDING", "body does not match its aihydro.entry/1 binding")
            continue
        if kind in _UNSEALED_KINDS:
            continue
        okr, rec, why = locate(e.get("record_location"))
        if not okr or not isinstance(rec, dict):
            not_ok[key] = ("VER-RECORD-SEAL", f"record unresolvable: {why}")
            continue
        if kind == "claim_revision" and rec.get("redacted_for_privacy") is True:
            stub_claims.add(eid.rpartition("@")[0])
        if kind in ("run", "claim_revision") and rec.get("session_id") != bundle["session_id"]:
            not_ok[key] = ("VER-SESSION", "record session_id differs from the bundle's session_id")
        elif kind == "run":
            if not record_seal_ok(rec):
                not_ok[key] = ("VER-RECORD-SEAL", "run record seal does not verify")
            elif rec.get("record_digest") != e.get("record_digest"):
                not_ok[key] = ("VER-RECORD-DIGEST", "record_digest differs from the bundle entry")
            elif rec.get("run_id") != eid:
                not_ok[key] = ("VER-RECORD-DIGEST", "record run_id differs from the bundle entry id")
            elif e.get("binding") is not None and (
                    not isinstance(rec.get("extra"), dict) or not isinstance(e["binding"], dict)
                    or rec["extra"].get("entry_digest") != e["binding"].get("digest")):
                not_ok[key] = ("VER-BINDING", "the declared binding is not the sealed one: the record's "
                                              "extra.entry_digest is missing or differs from the binding digest")
            elif body is not None and isinstance(rec.get("extra"), dict) and rec["extra"].get("entry_digest") \
                    and entry_digest(body) != rec["extra"]["entry_digest"]:
                not_ok[key] = ("VER-BINDING", "body does not match the sealed extra.entry_digest")
        elif kind == "claim_revision":
            if not verify_claim_revision(rec):
                not_ok[key] = ("VER-RECORD-SEAL", "claim revision seal does not verify")
            elif rec.get("record_digest") != e.get("record_digest"):
                not_ok[key] = ("VER-RECORD-DIGEST", "record_digest differs from the bundle entry")
            elif eid != f"{rec.get('claim_id')}@{rec.get('revision')}":
                not_ok[key] = ("VER-RECORD-DIGEST", "claim revision id differs from claim_id@revision")
            else:
                revisions.setdefault(rec["claim_id"], []).append((key, rec))
        elif kind == "basin_ref":
            try:
                digest_ok = c14n_digest(rec) == e.get("record_digest")
            except Exception:
                digest_ok = False
            if not digest_ok or not _basin_ref_ok(rec, eid):
                not_ok[key] = ("VER-RECORD-SEAL", "basin reference does not verify (digest, anchor id)")
            else:
                content_checks.append(key)
        else:   # approval and any later content-addressed kind: content digest only
            try:
                digest_ok = c14n_digest(rec) == e.get("record_digest")
            except Exception:
                digest_ok = False
            if not digest_ok:
                not_ok[key] = ("VER-RECORD-SEAL", "content digest differs from the bundle entry")
            else:
                content_checks.append(key)

    # content-addressed kinds are not seals: they must lie inside a run body bound to a sealed record
    # that verified in this same pass
    bound_prefixes = []
    for e in records:
        if e["kind"] == "run" and ("run", e["id"]) not in not_ok and e.get("binding") and e.get("body_location"):
            try:
                bound_prefixes.append(split_location(e["body_location"]))
            except ValueError:
                pass
    for key in content_checks:
        entry = next(x for x in records if (x["kind"], x["id"]) == key)
        path, toks = split_location(entry["record_location"])
        if not any(path == bp and toks[:len(bt)] == bt for bp, bt in bound_prefixes):
            not_ok[key] = ("VER-RECORD-SEAL", "content-addressed record does not lie inside a body bound to a "
                                              "verified sealed record")

    for claim_id, items in sorted(revisions.items()):
        items.sort(key=lambda it: it[1]["revision"])
        if not verify_chain([r for _k, r in items]):
            for k, _r in items:
                not_ok[k] = ("VER-CHAIN", f"claim {claim_id}: revision chain is broken, truncated at the head "
                                          "or has a gap")
        else:
            head = res["claim_heads"].get(claim_id)
            listed_n = sum(1 for x in records if x["kind"] == "claim_revision"
                           and x["id"].rpartition("@")[0] == claim_id)
            # the pin is compared only when every listed revision verified (else the seal failure is the finding)
            if head is not None and len(items) == listed_n and items[-1][1].get("revision_digest") != head:
                for k, _r in items:
                    not_ok[k] = ("VER-CHAIN", f"claim {claim_id}: head revision does not match the head the "
                                              "bundle pinned (tail cut or re-sealed)")

    sealed = [e for e in records if e["kind"] not in _UNSEALED_KINDS]
    bad_ids = sorted({eid for (_k, eid) in not_ok})
    res["records_total"] = len(sealed)
    res["records_verified"] = len(sealed) - len(not_ok)
    res["unverifiable_ids"] = bad_ids
    cov = bundle.get("coverage") if isinstance(bundle.get("coverage"), dict) else {}
    declared = cov.get("unverifiable_ids", [])
    for (kind, eid), (rule, why) in sorted(not_ok.items()):
        if eid in declared:
            withheld = (kind == "run" and eid in stub_runs) or (
                kind == "claim_revision" and eid.rpartition("@")[0] in stub_claims)
            if withheld:
                res["notes"].append(f"{kind}:{eid} declared unverifiable ({rule}: {why})")
            else:
                # a declaration cannot launder a defect: only a privacy-withheld row is acceptable partiality
                fail("VER-UNVERIFIABLE", f"declared unverifiable but not withheld for privacy ({rule}: {why})",
                     f"{kind}:{eid}")
        else:
            fail(rule, why, f"{kind}:{eid}")
    if cov.get("records_total") != res["records_total"] or cov.get("records_verified") != res["records_verified"] \
            or sorted(declared) != bad_ids:
        fail("VER-COVERAGE", f"declared coverage {cov.get('records_verified')}/{cov.get('records_total')} "
                             f"differs from recomputed {res['records_verified']}/{res['records_total']}")

    rr = bundle.get("run_rows")
    if isinstance(rr, dict):                  # core VER-RUN-ROWS: run_rows.sealed equals the run entries listed
        n_runs = sum(1 for x in records if x["kind"] == "run")
        # core VER-RUN-ROWS (0.2.5): a withheld row with a digest is a run entry counted under
        # withheld_for_privacy, not sealed; one without a digest has no entry. So
        # sealed <= run entries <= sealed + withheld_for_privacy.
        sealed_n = rr.get("sealed") if isinstance(rr.get("sealed"), int) else 0
        withheld_n = rr.get("withheld_for_privacy") if isinstance(rr.get("withheld_for_privacy"), int) else 0
        if not sealed_n <= n_runs <= sealed_n + withheld_n:
            fail("VER-RUN-ROWS", f"run_rows says {sealed_n} sealed and {withheld_n} withheld rows, which cannot "
                                 f"account for the {n_runs} run records the bundle lists "
                                 f"(need sealed <= entries <= sealed + withheld_for_privacy)")

    # gates are derived from verified, sealed-bound bodies; the declared list must equal them
    derived = set()
    for e in records:
        if e["kind"] != "run" or ("run", e["id"]) in not_ok or not e.get("binding") or not e.get("body_location"):
            continue
        okb, body, _w = locate(e["body_location"])
        okr, rec, _w = locate(e.get("record_location"))
        if (okb and okr and isinstance(rec, dict) and isinstance(rec.get("extra"), dict)
                and binding_ok(body, e["binding"]) and rec["extra"].get("entry_digest") == e["binding"].get("digest")
                and body.get("error_summary") in _GATE_CODES):
            derived.add((e["id"], body["error_summary"]))
    declared_g = {(g.get("run_id"), g.get("code")) for g in (bundle.get("gates") or []) if isinstance(g, dict)}
    if derived != declared_g:
        fail("VER-GATES", f"declared gates {sorted(declared_g)} differ from gates derived from the verified "
                          f"row bodies {sorted(derived)}")

    crate = capsule_dir / _CRATE_FILE
    if not crate.is_file():
        fail("VER-CRATE-REGEN", f"{_CRATE_FILE} is missing")
    bag = capsule_dir / _BAGIT_FILE
    if not bag.is_file():
        fail("VER-BAGIT", f"{_BAGIT_FILE} is missing (the exporter always writes it)")
    if bag.is_file():
        listed_bag = {}
        for line in bag.read_text(encoding="utf-8").splitlines():
            if line.strip():
                h, _, p = line.partition("  ")
                listed_bag[p] = h
        actual = {p: f["sha256"] for p, f in files.items()}
        if crate.is_file():
            actual[_CRATE_FILE] = hashlib.sha256(crate.read_bytes()).hexdigest()
        for p in sorted(set(listed_bag) | set(actual)):
            if listed_bag.get(p) != actual.get(p):
                fail("VER-BAGIT", f"{_BAGIT_FILE} and the files disagree", p)
    return res


def verify_bundle_with_core(capsule_dir: Path):
    """``aihydro_core.export.verify_crate`` when importable (adds crate regeneration), else ``None``."""
    try:
        from aihydro_core.export import verify_crate
    except Exception:
        return None
    try:
        return verify_crate(capsule_dir)
    except Exception as exc:                      # pragma: no cover - defensive
        class _Err:
            ok = False
            failures = [type("F", (), {"rule": "VER-CRATE-REGEN", "message": f"{type(exc).__name__}: {exc}",
                                       "entity": None})()]
        return _Err()


def check_manifest_run_counts(capsule_dir: Path, run_log: dict) -> str:
    """``""`` when ``run_log.json`` agrees with the manifest's ``run_records`` counts, else why not.

    A sealed row downgraded to a legacy row (its ``record`` deleted, then the body edited) still
    passes every per-row check, because a row with no record is "legacy". The export-time counts
    are the only thing that remembers it had one. The comparison also covers ``unsealable``,
    ``records_with_record_error`` and ``matches_exporting_environment``, so replacing a sealed row by
    a forged one (same row count) is seen when the replacement differs on any of them. They live in the capsule, so this catches an edit
    of ``run_log.json`` alone, or of the manifest alone; an attacker who rewrites both consistently
    (and the bundle that pins the manifest digest) is stopped only by an anchor outside the capsule.
    Older capsules without ``run_records`` are not checked.
    """
    try:
        manifest = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ""
    counts = manifest.get("run_records") if isinstance(manifest, dict) else None
    if not isinstance(counts, dict):
        return ""
    rows = [e for e in run_log.values()]
    recs = [e["record"] for e in rows if isinstance(e, dict) and isinstance(e.get("record"), dict)]
    v2 = len(recs)
    seen = {"run_log_rows": len(rows), "v2_records": v2, "legacy_unrecorded": len(rows) - v2,
            "unsealable": sum(1 for e in rows if isinstance(e, dict) and not isinstance(e.get("record"), dict)
                              and e.get("record_status") == "unsealable"),
            "records_with_record_error": sum(1 for r in recs if r.get("record_error"))}
    env = counts.get("environment")
    env_digest = env.get("env_digest") if isinstance(env, dict) else None
    if env_digest is not None and "matches_exporting_environment" in counts:
        # a delete plus a forged replacement keeps the three row counts equal but changes these
        seen["matches_exporting_environment"] = sum(1 for r in recs if r.get("env_digest") == env_digest)
    bad = {k: (counts.get(k), v) for k, v in seen.items() if k in counts and counts.get(k) != v}
    if not bad:
        return ""
    return ", ".join(f"{k}: manifest {m} vs observed {o}" for k, (m, o) in sorted(bad.items())) + \
        " (a sealed row may have been downgraded to legacy, or rows removed or added)"


def crate_marker_ok(capsule_dir: Path, out=print) -> bool:
    """A capsule with no bundle.json is "pre-crate" only if nothing says a crate was written.

    The exporter writes ``manifest["crate"] = {"expected": true}`` before the crate step (and rewrites it
    to ``{"expected": false, "error": ...}`` if the crate could not be built). Claim revisions are carried
    only by exporters that also write a crate. So a missing bundle next to either marker is a deletion,
    not an old capsule. An attacker who also edits the manifest back to the pre-crate shape is
    indistinguishable from a genuine old capsule inside the capsule; only an external anchor helps.
    """
    try:
        manifest = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        manifest = {}
    marker = manifest.get("crate") if isinstance(manifest, dict) else None
    expected = isinstance(marker, dict) and marker.get("expected") is True
    carried = (capsule_dir / "records" / "claim_revisions.json").exists() or (
        isinstance(manifest.get("claim_revisions"), dict) and manifest["claim_revisions"].get("file"))
    declined = isinstance(marker, dict) and marker.get("expected") is False
    present = [n for n in (_BUNDLE_FILE, _CRATE_FILE, _BAGIT_FILE) if (capsule_dir / n).exists()]
    if expected or (carried and not declined) or present:
        why = ("the manifest says a crate was written" if expected else
               "claim revisions are carried" if carried and not declined else "other crate files exist")
        out(f"FAIL  {_BUNDLE_FILE} is missing but {why}: the crate files were removed or never completed")
        return False
    if declined:
        out(f"NOTE  no bundle.json: the exporter recorded that the crate was not written "
            f"({str(marker.get('error'))[:120]})")
    else:
        out("Bundle: no bundle.json (this capsule predates the crate export)")
    return True


def check_session_ids(capsule_dir: Path, run_log: dict, out=print) -> list:
    """Every sealed run row and claim revision must name this capsule's session.

    The expected id is the manifest's ``session_id`` (written at export) or, for older capsules,
    ``session.json``'s. Outside the bundle path nothing else compared them (fault matrix F8).
    """
    expected = None
    try:
        expected = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8")).get("session_id")
    except (OSError, ValueError):
        pass
    if not isinstance(expected, str) or not expected:
        try:
            expected = json.loads((capsule_dir / "session.json").read_text(encoding="utf-8")).get("session_id")
        except (OSError, ValueError):
            expected = None
    if not isinstance(expected, str) or not expected:
        return []
    bad = []
    for rid, row in sorted(run_log.items()):
        rec = row.get("record") if isinstance(row, dict) else None
        if isinstance(rec, dict) and rec.get("session_id") != expected:
            bad.append(f"run {rid}")
    cpath = capsule_dir / "records" / "claim_revisions.json"
    if cpath.exists():
        try:
            doc = json.loads(cpath.read_text(encoding="utf-8"))
        except ValueError:
            doc = {}
        for cid, item in sorted((doc.get("claims") or {}).items()):
            for row in (item.get("rows") or []) if isinstance(item, dict) else []:
                if isinstance(row, dict) and row.get("session_id") != expected:
                    bad.append(f"claim {cid}@{row.get('revision')}")
    for what in bad:
        out(f"FAIL  {what} names a session other than this capsule's ({expected})")
    return bad


_HEAD_FIELDS = (("claim", "text"), ("claim_type", "claim_type"), ("status", "status"),
                ("confidence", "confidence"), ("confidence_rationale", "confidence_rationale"),
                ("limitations", "limitations"))


def check_claims_against_heads(capsule_dir: Path, out=print) -> list:
    """session.json's claim must agree with its sealed head revision on the authority fields.

    Editing the claim text in the capsule and regenerating the manifest and bundle changes nothing the
    other checks compare (fault matrix M06e). The head revision is sealed in the chain; the session
    claim is a mutable working copy. Only fields the revision projects are compared; a head carried as
    a privacy stub, or a claim without a chain, is skipped.
    """
    try:
        doc = json.loads((capsule_dir / "records" / "claim_revisions.json").read_text(encoding="utf-8"))
        claims = json.loads((capsule_dir / "session.json").read_text(encoding="utf-8")).get("claims")
    except (OSError, ValueError):
        return []
    if not isinstance(claims, dict):
        return []
    bad = []
    for cid, item in sorted((doc.get("claims") or {}).items()):
        rows = item.get("rows") if isinstance(item, dict) and item.get("status") == "ok" else None
        claim = claims.get(cid)
        if not rows or not isinstance(claim, dict) or not isinstance(rows[-1], dict) \
                or rows[-1].get(REDACTED_KEY) or not isinstance(rows[-1].get("content"), dict):
            continue
        head = rows[-1]["content"]
        diff = [sk for sk, hk in _HEAD_FIELDS if sk in claim and hk in head and claim[sk] != head[hk]]
        if diff:
            bad.append((cid, diff))
            out(f"FAIL  claim {cid}: session.json differs from the sealed head revision "
                f"{rows[-1].get('revision')} in {', '.join(diff)} (edited after the last revision?)")
    return bad


def verify_claims(capsule_dir: Path, heads=None, out=print):
    """Verify ``records/claim_revisions.json`` chain by chain. ``None`` when the capsule has none."""
    path = capsule_dir / "records" / "claim_revisions.json"
    if not path.exists():
        return None
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        out("FAIL  records/claim_revisions.json is not valid JSON")
        return {"verified": 0, "partial": 0, "failed": 1, "corrupt": 0, "claims": 0, "failures": 1}
    verdicts = verify_exported(doc, heads)
    s = {"verified": 0, "partial": 0, "failed": 0, "corrupt": 0, "claims": len(verdicts), "failures": 0}
    for cid, v in sorted(verdicts.items()):
        st = v["status"]
        if st == "verified":
            s["verified"] += 1
            out(f"PASS  claim {cid}: {v['revisions']} revision(s), {v['detail']}")
        elif st == "partial":
            s["partial"] += 1
            out(f"NOTE  claim {cid}: {v['detail']}; redacted for privacy (neither verified nor failed)")
        elif st == "corrupt_at_export":
            s["corrupt"] += 1
            s["failures"] += 1
            out(f"FAIL  claim {cid}: {v['detail']}")
        else:
            s["failed"] += 1
            s["failures"] += 1
            out(f"FAIL  claim {cid}: {v['detail']}")
    return s


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #

def replay_status(integrity_ok: bool, live: bool, n_comparisons: int, comparisons_ok: bool,
                  partial: bool = False) -> str:
    """The strongest level actually reached. Never ``recomputed``.

    ``partial`` is accepted for compatibility and ignored: partial coverage (some
    rows redacted for privacy) is reported as coverage, not as a level, so a
    partially redacted capsule can still report a successful cross-check (R2).
    The legacy persisted string ``archive_integrity_partial`` reads as
    ``archive_integrity`` with coverage below 1.
    """
    if not integrity_ok:
        return "not_performed"
    if live and n_comparisons > 0 and comparisons_ok:
        return "cross_check"
    return "archive_integrity"


def assess(capsule_dir: Path, live: bool = False, tolerance: float = DEFAULT_TOLERANCE, out=print,
           allowed_signers=None, check_crate: bool = True) -> dict:
    """Run every check and return the assessment (``run`` prints it and maps it to an exit code).

    ``check_crate=False`` skips the bundle/crate checks (used by the exporter before the
    bundle exists). The exporter and replay.py therefore share one code path.
    """
    hashes_ok, hash_results = verify_hashes(capsule_dir, out=out)
    n_pass = sum(1 for r in hash_results if r["status"] == "pass")
    n_bad = sum(1 for r in hash_results if r["status"] != "pass")
    out(f"\nHash check: {n_pass} pass, {n_bad} fail")

    records_ok = True
    summary = None
    rl_path = capsule_dir / "run_log.json"
    if rl_path.exists():
        summary = verify_run_log(json.loads(rl_path.read_text(encoding="utf-8")))
        for run_id, why in summary["failures"]:
            out(f"FAIL  record {run_id}: {why}")
        records_ok = not summary["failures"]
        why_counts = check_manifest_run_counts(capsule_dir, json.loads(rl_path.read_text(encoding="utf-8")))
        if why_counts:
            out(f"FAIL  run_log.json does not match the manifest's run_records counts: {why_counts}")
            records_ok = False
        out(f"Run records: {summary['verified']} of {summary['v2_records']} v2 records verify; "
            f"{summary['unbound']} sealed but unbound to their row; "
            f"{summary['legacy']} legacy rows have no record ({summary['unsealable']} of them marked "
            f"unsealable by the recorder); {summary['record_errors']} carry a record_error")
        for run_id, why in summary["unsealable_rows"]:
            out(f"NOTE  run {run_id}: unsealable: {why}")
        if summary["redacted"]:
            out(f"NOTE  {summary['redacted']} run-log row(s) redacted for privacy "
                "(not verifiable from capsule): neither verified nor failed")
    else:
        out("Run records: run_log.json not found")

    bindings_ok = verify_data_bindings(capsule_dir, out=out)
    session_bad = check_session_ids(capsule_dir, json.loads(rl_path.read_text(encoding="utf-8"))
                                    if rl_path.exists() else {}, out=out)
    head_bad = check_claims_against_heads(capsule_dir, out=out)
    if session_bad or head_bad:
        records_ok = False

    bundle_res = verify_bundle(capsule_dir) if check_crate else None
    heads = bundle_res["claim_heads"] if bundle_res else None
    claims = verify_claims(capsule_dir, heads, out=out)
    claims_ok = claims is None or claims["failures"] == 0
    crate_ok = True
    coverage = None
    if bundle_res is not None:
        out("")
        for rule, entity, message in bundle_res["failures"]:
            out(f"FAIL  {rule}{' ' + entity if entity else ''}: {message}")
        for note in bundle_res["notes"]:
            out(f"NOTE  {note}")
        crate_ok = bundle_res["ok"]
        coverage = bundle_res["coverage"]
        out(f"Bundle: {bundle_res['records_verified']} of {bundle_res['records_total']} sealed records verify "
            f"({'ok' if crate_ok else 'FAILED'}); crate regeneration is not checked by this stdlib mirror")
        core_res = verify_bundle_with_core(capsule_dir)
        if core_res is None:
            out("NOTE  stdlib mirror only: not checked here are crate regeneration and byte comparison, "
                "core's structural/honesty validator (VER-VALIDATE), and the field validation of "
                "bundle.json (types of optional fields, SPDX strings). Run aihydro_core.export verify for those.")
        if core_res is not None:
            for f in core_res.failures:
                out(f"FAIL  {f.rule}{' ' + f.entity if getattr(f, 'entity', None) else ''}: {f.message}")
            crate_ok = crate_ok and core_res.ok
            out("Crate regenerated by aihydro_core and byte-compared: "
                + ("ok" if core_res.ok else "FAILED"))
            try:
                import aihydro_core
                made = (json.loads((capsule_dir / "bundle.json").read_text(encoding="utf-8")).get("exporter") or {}
                        ).get("projection")
                if made:
                    out(f"NOTE  crate projected by {made}; regenerated here with aihydro-core "
                        f"{getattr(aihydro_core, '__version__', '?')}"
                        + ("" if core_res.ok else " (a version difference can explain a regeneration mismatch)"))
            except Exception:
                pass
    elif check_crate:
        crate_ok = crate_marker_ok(capsule_dir, out)

    out("")
    approvals_ok = verify_approvals(capsule_dir, allowed_signers, out=out)["failed"] == 0

    comparisons, comparisons_ok = [], True
    if live:
        comparisons, skipped = live_cross_check(capsule_dir, tolerance)
        for c in comparisons:
            if c["status"] == "pass":
                out(f"PASS  {c['run_id']}:{c['key']}  {c['expected']:.4g} ~ {c['actual']:.4g}")
            else:
                out(f"FAIL  {c['run_id']}:{c['key']}  expected={c['expected']:.4g}  "
                    f"got={c['actual']:.4g}  ({c['deviation_pct']:.1f}%)")
        comparisons_ok = all(c["status"] == "pass" for c in comparisons)
        for run_id, why in skipped:
            out(f"SKIP  {run_id}: {why}")

    integrity_ok = hashes_ok and records_ok and bindings_ok and claims_ok and crate_ok
    if not hash_results and not (summary is not None and summary["v2_records"]):
        integrity_ok = False        # nothing was actually checked
        out("FAIL  archive has no files and no records; nothing was verified.")
    status = replay_status(integrity_ok, live, len(comparisons), comparisons_ok)
    partial = bool((summary and summary["redacted"]) or (claims and claims["partial"])
                   or (coverage and coverage.get("records_verified") != coverage.get("records_total")))
    out(f"\nreplay_status: {status}")
    if integrity_ok and coverage:
        out(f"coverage: {coverage.get('records_verified')} of {coverage.get('records_total')} sealed records "
            f"verified" + ("; partial: some records are withheld or unverifiable (see NOTE lines)" if partial else ""))
    elif integrity_ok and partial:
        out("coverage: partial: some records are withheld for privacy and are neither verified nor failed")
    out("recomputation: not_performed")
    if live:
        out(f"comparisons: {len(comparisons)}")
    return {"status": status, "integrity_ok": integrity_ok, "approvals_ok": approvals_ok,
            "comparisons": comparisons, "comparisons_ok": comparisons_ok, "live": live,
            "partial": partial, "coverage": coverage, "hashes_ok": hashes_ok, "records_ok": records_ok,
            "claims": claims, "bundle": bundle_res}


def run(capsule_dir: Path, live: bool = False, tolerance: float = DEFAULT_TOLERANCE, out=print,
        allowed_signers=None) -> int:
    a = assess(capsule_dir, live, tolerance, out, allowed_signers)
    if not (a["integrity_ok"] and a["comparisons_ok"] and a["approvals_ok"]):
        return 1
    if live and not a["comparisons"]:
        out("FAIL  --live found no comparable values; nothing was cross-checked.")
        return 2
    return 0


def main(argv=None, capsule_dir: Path | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    tolerance = DEFAULT_TOLERANCE
    allowed_signers = None
    for i, arg in enumerate(argv):
        if arg.startswith("--tolerance="):
            try:
                tolerance = float(arg.split("=", 1)[1])
            except ValueError:
                pass
        elif arg.startswith("--allowed-signers="):
            allowed_signers = arg.split("=", 1)[1]
        elif arg == "--allowed-signers":
            if i + 1 >= len(argv):
                print("FAIL  --allowed-signers needs a file argument")
                return 1
            allowed_signers = argv[i + 1]
    return run(capsule_dir or Path(__file__).parent, live="--live" in argv, tolerance=tolerance,
               allowed_signers=allowed_signers)


def source_text() -> str:
    """The text written to a capsule as ``replay.py`` (this file, verbatim)."""
    return Path(__file__).read_text(encoding="utf-8")



def _listed_data_paths(capsule_dir: Path) -> set:
    """data/ paths the manifest claims the capsule carries (files + data_artifacts)."""
    try:
        m = json.loads((capsule_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except Exception:
        return set()
    listed = {e.get("path") for e in m.get("files") or [] if isinstance(e, dict)}
    for art in m.get("data_artifacts") or []:
        if isinstance(art, dict):
            listed.add(art.get("path"))
            listed.add(art.get("retained_artifact", {}).get("path") if isinstance(art.get("retained_artifact"), dict) else None)
    return {x for x in listed if isinstance(x, str) and x.startswith("data/")}

if __name__ == "__main__":
    sys.exit(main())
