"""
Defensibility Report: session-level scientific accountability document.

build_defensibility_report(session, session_id, today) → (markdown_str, summary_dict)

Sections
--------
1. Header — site, session ID, export date, platform version
2. Audit Summary — audit_prose results on session.interpretation (pass/fail,
   numeric_coverage, any violations listed verbatim)
3. Uncertainty Coverage — per-slot table: which computed slots have CI
   estimates attached (_uncertainty key present)
4. Claims Register — all session.claims with status / confidence / evidence;
   confirmatory (pre-registered) vs exploratory (post-hoc) labeling
5. Validator Flags — quality_flags extracted from run_log entries; deduplicated
   by (validator, status) pair
6. Numbers Manifest — every cited numeric from run_log.key_outputs, bound to
   a run_id (generalises papers/platform/numbers_manifest.json to any session)
7. Pre-registration Plan — locked hypothesis and planned analyses (if filed);
   plan-vs-executed diff showing which planned analyses were actually run

Pure function: no file I/O, no MCP imports, no network.
Callers (export_session) handle writing to disk.
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ai_hydro.session.store import HydroSession

log = logging.getLogger("ai_hydro.reports.defensibility")

# Slots that can carry _uncertainty in their data dict
_QUANT_SLOTS = frozenset({
    "signatures", "geomorphic", "model", "baseflow",
    "flood_frequency", "streamflow", "cn",
})

# Status display for claims
_STATUS_EMOJI = {
    "proposed": "○",
    "tested": "◑",
    "weakly_supported": "◔",
    "supported": "●",
    "contradicted": "✗",
    "retracted": "⊘",
    "inconclusive": "?",
    "superseded": "→",
}


def build_defensibility_report(
    session: "HydroSession",
    session_id: str,
    today: str,
) -> tuple[str, dict]:
    """
    Build a Markdown defensibility report for the given session.

    Returns:
        (markdown_text, summary_dict)

    summary_dict keys::

        audit_passed            bool | None — None when no interpretation exists
        n_violations            int
        numeric_coverage        float       — 0.0–1.0; 1.0 when no numbers exist
        n_claims                int
        n_with_uncertainty      int         — quant slots with CI coverage
        n_quant_slots           int         — quant slots computed at all
        uncertainty_coverage_pct float      — 0.0–100.0
        n_cited_numbers         int         — rows in numbers manifest
        n_validator_flags       int
        prereg_present          bool        — True if a locked research plan exists
        n_confirmatory_claims   int         — claims with prereg_id set
        n_planned_analyses      int         — analyses listed in the plan (0 if no plan)
        n_executed_planned      int         — planned analyses that were actually run
    """
    lines: list[str] = []
    run_log: dict[str, dict] = session.get("_run_log") or {}

    # ─────────────────────────────────────────────────────────────────────────
    # 1. Header
    # ─────────────────────────────────────────────────────────────────────────
    display = session.site_name or session.site_id or session_id
    lines += [
        f"# Defensibility Report: {display}",
        "",
        f"**Session ID**: `{session_id}`",
        f"**Site**: {session.site_id or '—'}" + (
            f" ({session.site_type})" if getattr(session, "site_type", None) else ""
        ),
        f"**Export date**: {today}",
        f"**Platform**: AI-Hydro  ",
        "",
        "> This report is auto-generated by `export_session(format='defensibility_report')`.",
        "> Every number in the Numbers Manifest is traced to a `run_id` produced by a",
        "> deterministic, logged tool call. Do not edit this file manually.",
        "",
    ]

    # ─────────────────────────────────────────────────────────────────────────
    # 2. Audit Summary
    # ─────────────────────────────────────────────────────────────────────────
    audit_passed: bool | None = None
    n_violations = 0
    numeric_coverage: float = 1.0

    lines += ["---", "", "## 2. Audit Summary", ""]

    if session.interpretation:
        try:
            from ai_hydro.audit import audit_prose

            report = audit_prose(session.interpretation, session_id)
            audit_passed = report.passed
            n_violations = len(report.violations)
            numeric_coverage = report.numeric_coverage

            status_icon = "✅" if report.passed else "❌"
            lines += [
                f"**Status**: {status_icon} {'PASS' if report.passed else 'FAIL'}  ",
                f"**Numeric coverage**: {report.numeric_coverage * 100:.1f}%  ",
                f"**Violations**: {n_violations}  ",
                "",
            ]
            if report.violations:
                lines += [
                    "### Violations",
                    "",
                    "| # | Type | Number | Context |",
                    "|---|------|--------|---------|",
                ]
                for i, v in enumerate(report.violations, 1):
                    vtype = getattr(v, "violation_type", getattr(v, "type", "?"))
                    num = getattr(v, "number", "—")
                    ctx = str(getattr(v, "context", ""))[:80].replace("|", "\\|")
                    lines.append(f"| {i} | `{vtype}` | `{num}` | {ctx} |")
                lines.append("")
        except Exception as exc:
            log.warning("Audit failed in defensibility report (non-fatal): %s", exc)
            lines += [
                "_Audit unavailable — interpretation could not be audited._",
                f"> `{exc}`",
                "",
            ]
    else:
        lines += [
            "_No interpretation found. Call `write_research_interpretation` to author",
            "the scientific summary, then re-export to include the audit result._",
            "",
        ]

    # ─────────────────────────────────────────────────────────────────────────
    # 3. Uncertainty Coverage
    # ─────────────────────────────────────────────────────────────────────────
    lines += ["---", "", "## 3. Uncertainty Coverage", ""]

    computed = session.computed()
    quant_computed = [s for s in computed if s in _QUANT_SLOTS]
    n_quant_slots = len(quant_computed)
    n_with_uncertainty = 0

    if quant_computed:
        lines += [
            "| Slot | Computed | CIs present | Methods |",
            "|------|----------|-------------|---------|",
        ]
        for slot in sorted(computed):
            result = session.get(slot)
            if result is None:
                continue
            data = result.get("data") or {}
            computed_at = (result.get("meta") or {}).get("computed_at", "—")[:10]
            unc = data.get("_uncertainty")
            if slot in _QUANT_SLOTS:
                if unc:
                    n_with_uncertainty += 1
                    methods = ", ".join(
                        sorted({v.get("method", "?") for v in unc.values()
                                if isinstance(v, dict)})
                    ) or "—"
                    ci_cell = f"✅ ({len(unc)} metrics)"
                else:
                    methods = "—"
                    ci_cell = "❌"
            else:
                ci_cell = "n/a"
                methods = "—"
            lines.append(f"| `{slot}` | {computed_at} | {ci_cell} | {methods} |")
        lines.append("")
    else:
        lines += ["_No quantitative analysis slots computed yet._", ""]

    uncertainty_coverage_pct = (
        100.0 * n_with_uncertainty / n_quant_slots if n_quant_slots else 100.0
    )
    lines += [
        f"**Uncertainty coverage**: {n_with_uncertainty}/{n_quant_slots} "
        f"quantitative slots ({uncertainty_coverage_pct:.0f}%)  ",
        "",
    ]

    # ─────────────────────────────────────────────────────────────────────────
    # 4. Claims Register
    # ─────────────────────────────────────────────────────────────────────────
    lines += ["---", "", "## 4. Claims Register", ""]

    claims = session.claims or {}
    n_claims = len(claims)
    n_confirmatory_claims = sum(
        1 for c in claims.values() if c.get("prereg_id")
    )

    if claims:
        lines += [
            "| ID | Status | Type | Confidence | Pre-reg | Evidence | Limitations | Statement |",
            "|----|--------|------|------------|---------|----------|-------------|-----------|",
        ]
        for cid, c in sorted(claims.items()):
            status = c.get("status", "?")
            icon = _STATUS_EMOJI.get(status, "?")
            ctype = c.get("claim_type", c.get("claimType", "?"))[:12]
            conf = c.get("confidence", "?")
            stmt = str(c.get("claim", c.get("statement", "—")))[:80].replace("|", "\\|")
            evidence_spans = c.get("evidence_spans", c.get("evidenceSpans", []))
            n_ev = len(evidence_spans) if isinstance(evidence_spans, list) else 0
            n_lim = len(c.get("limitations", []))
            prereg_cell = f"✅ confirmatory" if c.get("prereg_id") else "○ exploratory"
            lines.append(
                f"| `{cid[:16]}` | {icon} {status} | {ctype} | {conf} "
                f"| {prereg_cell} | {n_ev} spans | {n_lim} | {stmt} |"
            )
        lines.append("")

        # Status breakdown
        from collections import Counter
        status_counts = Counter(c.get("status", "?") for c in claims.values())
        breakdown = ", ".join(
            f"{_STATUS_EMOJI.get(s, '?')} {s}: {n}"
            for s, n in sorted(status_counts.items())
        )
        n_expl = n_claims - n_confirmatory_claims
        lines += [
            f"**Summary**: {breakdown}  ",
            f"**Pre-registration**: {n_confirmatory_claims} confirmatory, "
            f"{n_expl} exploratory  ",
            "",
        ]
    else:
        lines += [
            "_No claims registered. Call `add_claim` to record scientific conclusions._",
            "",
        ]

    # ─────────────────────────────────────────────────────────────────────────
    # 5. Validator Flags
    # ─────────────────────────────────────────────────────────────────────────
    lines += ["---", "", "## 5. Validator Flags", ""]

    # Collect all quality_flags from run_log entries
    all_flags: list[dict] = []
    for run_id, entry in run_log.items():
        for flag in entry.get("key_outputs", {}).get("_quality_flags", []):
            if isinstance(flag, dict):
                all_flags.append({
                    "run_id": run_id,
                    "tool": entry.get("tool_name", "?"),
                    "validator": flag.get("validator", "?"),
                    "status": flag.get("status", "?"),
                })

    n_validator_flags = len(all_flags)

    if all_flags:
        lines += [
            "| Run ID | Tool | Validator | Status |",
            "|--------|------|-----------|--------|",
        ]
        seen: set[tuple] = set()
        for f in all_flags:
            key = (f["run_id"], f["validator"])
            if key in seen:
                continue
            seen.add(key)
            icon = "⚠️" if f["status"] == "warning" else ("✅" if f["status"] == "pass" else "ℹ️")
            lines.append(
                f"| `{f['run_id'][:28]}` | `{f['tool'][:28]}` "
                f"| `{f['validator']}` | {icon} {f['status']} |"
            )
        lines.append("")
    else:
        # Also check session slots directly for quality_flags (some tools store them there)
        slot_flags_found = False
        for slot in computed:
            result = session.get(slot)
            if not result:
                continue
            qf = result.get("quality_flags") or []
            for flag in qf:
                if not slot_flags_found:
                    lines += [
                        "| Slot | Validator | Status |",
                        "|------|-----------|--------|",
                    ]
                    slot_flags_found = True
                icon = "⚠️" if flag.get("status") == "warning" else "✅"
                lines.append(
                    f"| `{slot}` | `{flag.get('validator', '?')}` "
                    f"| {icon} {flag.get('status', '?')} |"
                )
        if not slot_flags_found:
            lines += ["_No validator flags recorded in this session._", ""]
        else:
            lines.append("")

    # ─────────────────────────────────────────────────────────────────────────
    # 6. Numbers Manifest
    # ─────────────────────────────────────────────────────────────────────────
    lines += ["---", "", "## 6. Numbers Manifest", ""]
    lines += [
        "Every numeric value cited from a tool call, bound to its `run_id`.",
        "Use these bindings to verify any number in the scientific interpretation.",
        "",
    ]

    rows: list[dict] = []
    for run_id, entry in sorted(run_log.items()):
        tool = entry.get("tool_name", "?")
        ts = entry.get("timestamp", "")[:10]
        for k, v in entry.get("key_outputs", {}).items():
            if k.startswith("_") or not isinstance(v, (int, float)):
                continue
            rows.append({"run_id": run_id, "tool": tool, "key": k, "value": v, "date": ts})

    n_cited_numbers = len(rows)

    if rows:
        lines += [
            "| # | Key | Value | Run ID | Tool | Date |",
            "|---|-----|-------|--------|------|------|",
        ]
        for i, r in enumerate(rows, 1):
            val_str = f"{r['value']:.4g}" if isinstance(r["value"], float) else str(r["value"])
            lines.append(
                f"| {i} | `{r['key']}` | {val_str} "
                f"| `{r['run_id'][:24]}` | `{r['tool'][:24]}` | {r['date']} |"
            )
        lines.append("")
    else:
        lines += [
            "_No cited numbers found. Run scientific analyses to populate the manifest._",
            "",
        ]

    # ─────────────────────────────────────────────────────────────────────────
    # 7. Pre-registration Plan
    # ─────────────────────────────────────────────────────────────────────────
    lines += ["---", "", "## 7. Pre-registration Plan", ""]

    plan: dict | None = session.get("_research_plan")
    prereg_present = bool(plan and plan.get("locked"))
    n_planned_analyses = 0
    n_executed_planned = 0

    if prereg_present:
        assert plan is not None  # guarded above
        n_planned_analyses = len(plan.get("planned_analyses", []))
        lines += [
            f"**Pre-registration ID**: `{plan.get('prereg_id', '—')}`  ",
            f"**Locked at**: {plan.get('locked_at', '—')[:19]} UTC  ",
            f"**Content hash**: `{plan.get('content_hash', '—')}`  ",
            "",
            "### Hypothesis",
            "",
            f"> {plan.get('hypothesis', '—')}",
            "",
            "### Planned Analyses vs. Executed",
            "",
        ]

        # Derive executed tools from run_log
        executed_tools: set[str] = {
            entry.get("tool_name", "") for entry in run_log.values()
            if entry.get("tool_name")
        }
        computed_slots: set[str] = set(session.computed())

        lines += [
            "| # | Planned Analysis | Executed |",
            "|---|-----------------|---------|",
        ]
        for i, pa in enumerate(plan.get("planned_analyses", []), 1):
            pa_lower = pa.lower().replace(" ", "_")
            # Match if the planned analysis name appears in any executed tool name
            # or matches a computed slot name
            executed = any(
                pa_lower in t.lower() or t.lower() in pa_lower
                for t in executed_tools | computed_slots
            )
            if executed:
                n_executed_planned += 1
            tick = "✅" if executed else "○ not yet run"
            lines.append(f"| {i} | {pa} | {tick} |")
        lines.append("")

        n_not_run = n_planned_analyses - n_executed_planned
        lines += [
            f"**Coverage**: {n_executed_planned}/{n_planned_analyses} planned analyses "
            f"executed ({n_not_run} pending)  ",
            "",
        ]

        if n_confirmatory_claims:
            lines += [
                f"**Confirmatory claims** (filed with this prereg_id): "
                f"{n_confirmatory_claims}  ",
                "",
            ]
        else:
            lines += [
                "_No claims have been filed as confirmatory yet. Pass "
                f"`prereg_id='{plan.get('prereg_id', '')}'` to `add_claim` "
                "to mark a claim as pre-planned._",
                "",
            ]
    else:
        lines += [
            "_No pre-registration found for this session. All claims are exploratory._",
            "",
            "> To pre-register a hypothesis before running analyses, call",
            "> `register_research_plan(session_id, hypothesis, planned_analyses)`",
            "> at the start of the session. The plan is locked immediately and",
            "> cannot be modified.",
            "",
        ]

    lines += [
        "---",
        "",
        f"> Report generated by AI-Hydro · {today}",
    ]

    markdown = "\n".join(lines)

    summary: dict[str, Any] = {
        "audit_passed": audit_passed,
        "n_violations": n_violations,
        "numeric_coverage": numeric_coverage,
        "n_claims": n_claims,
        "n_with_uncertainty": n_with_uncertainty,
        "n_quant_slots": n_quant_slots,
        "uncertainty_coverage_pct": round(uncertainty_coverage_pct, 1),
        "n_cited_numbers": n_cited_numbers,
        "n_validator_flags": n_validator_flags,
        "prereg_present": prereg_present,
        "n_confirmatory_claims": n_confirmatory_claims,
        "n_planned_analyses": n_planned_analyses,
        "n_executed_planned": n_executed_planned,
    }
    return markdown, summary
