"""
AI-Hydro Project Session
=========================
Project-level research state that spans multiple gauges, topics, and data
sources — not just a single USGS gauge.

A Project is the top-level unit of research organisation in AI-Hydro v1.2+.
Each project owns:
  - A collection of associated gauge sessions (referenced by gauge_id)
  - A literature folder (user drops PDFs / text files there)
  - An auto-generated literature index (literature_index.md)
  - A project-level research journal (journal entries written by the agent)
  - Free-form notes and topic tags

Storage layout
--------------
~/.aihydro/
    projects/
        <project_name>/
            project.json          ← project metadata (this class serialises here)
            literature/           ← user drops papers/docs here
            literature_index.md   ← auto-generated by index_literature tool
    sessions/
        <gauge_id>.json           ← gauge sessions (unchanged, referenced by project)
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_PROJECTS_DIR = Path.home() / ".aihydro" / "projects"
_SESSIONS_DIR = Path.home() / ".aihydro" / "sessions"

# Project root: python/ai_hydro/session/project.py → up 4 levels
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_RESEARCH_MD = _PROJECT_ROOT / ".clinerules" / "research.md"


class ProjectSession:
    """Project-level research state spanning multiple gauges and topics."""

    def __init__(self, name: str) -> None:
        self.name: str = name
        self.description: str = ""
        self.gauge_ids: list[str] = []          # associated USGS gauges
        self.topics: list[str] = []             # free-form topic tags
        self.literature_dir: str | None = None  # path to literature folder
        self.journal: list[dict] = []           # timestamped experiment log entries
        self.notes: list[str] = []              # free-form notes
        self.created_at: str = datetime.now(timezone.utc).isoformat()
        self.updated_at: str = self.created_at

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------

    @classmethod
    def _dir(cls, name: str) -> Path:
        return _PROJECTS_DIR / name

    @classmethod
    def _path(cls, name: str) -> Path:
        return cls._dir(name) / "project.json"

    @property
    def literature_path(self) -> Path:
        """Default literature folder inside the project directory."""
        return self._dir(self.name) / "literature"

    @property
    def literature_index_path(self) -> Path:
        return self._dir(self.name) / "literature_index.md"

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, name: str) -> ProjectSession:
        """Load existing project or return a fresh one."""
        path = cls._path(name)
        if not path.exists():
            return cls(name)
        with open(path) as f:
            raw = json.load(f)
        p = cls(name)
        p.description = raw.get("description", "")
        p.gauge_ids = raw.get("gauge_ids", [])
        p.topics = raw.get("topics", [])
        p.literature_dir = raw.get("literature_dir")
        p.journal = raw.get("journal", [])
        p.notes = raw.get("notes", [])
        p.created_at = raw.get("created_at", p.created_at)
        p.updated_at = raw.get("updated_at", p.updated_at)
        return p

    @classmethod
    def list_all(cls) -> list[str]:
        """Return names of all existing projects."""
        if not _PROJECTS_DIR.exists():
            return []
        return [d.name for d in _PROJECTS_DIR.iterdir() if d.is_dir()]

    def save(self) -> None:
        self.updated_at = datetime.now(timezone.utc).isoformat()
        self._dir(self.name).mkdir(parents=True, exist_ok=True)
        with open(self._path(self.name), "w") as f:
            json.dump(self._to_raw(), f, indent=2)
        self.write_research_context()

    def _to_raw(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "gauge_ids": self.gauge_ids,
            "topics": self.topics,
            "literature_dir": self.literature_dir,
            "journal": self.journal,
            "notes": self.notes,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    # ------------------------------------------------------------------
    # Gauge management
    # ------------------------------------------------------------------

    def add_gauge(self, gauge_id: str) -> bool:
        """Associate a gauge with this project. Returns True if newly added."""
        if gauge_id not in self.gauge_ids:
            self.gauge_ids.append(gauge_id)
            return True
        return False

    def remove_gauge(self, gauge_id: str) -> bool:
        """Disassociate a gauge. Returns True if it was present."""
        if gauge_id in self.gauge_ids:
            self.gauge_ids.remove(gauge_id)
            return True
        return False

    # ------------------------------------------------------------------
    # Journal
    # ------------------------------------------------------------------

    def log_entry(self, text: str, tags: list[str] | None = None) -> dict:
        """Add a timestamped journal entry."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "text": text,
            "tags": tags or [],
        }
        self.journal.append(entry)
        return entry

    def search_journal(self, query: str) -> list[dict]:
        """Full-text search over journal entries."""
        q = query.lower()
        return [e for e in self.journal if q in e.get("text", "").lower()
                or any(q in t.lower() for t in e.get("tags", []))]

    # ------------------------------------------------------------------
    # Cross-session analytics
    # ------------------------------------------------------------------

    def gauge_summaries(self) -> list[dict]:
        """Load and summarise all associated gauge sessions."""
        from ai_hydro.session.store import HydroSession
        results = []
        for gid in self.gauge_ids:
            try:
                s = HydroSession.load(gid)
                results.append(s.summary())
            except Exception:
                results.append({"gauge_id": gid, "error": "could not load"})
        return results

    def search_experiments(self, query: str) -> list[dict]:
        """
        Search across all gauge sessions for results matching the query.

        Searches JSON representations of stored slot data. Useful for
        questions like "which gauges have BFI > 0.6" (agent can filter
        from the returned snippets) or "show me basins where I ran LSTM".
        """
        from ai_hydro.session.store import HydroSession
        q = query.lower()
        matches: list[dict] = []
        for gid in self.gauge_ids:
            try:
                s = HydroSession.load(gid)
                for slot in s.computed():
                    result = s.get(slot)
                    if not result:
                        continue
                    blob = json.dumps(result).lower()
                    notes_blob = " ".join(s.notes).lower()
                    if q in blob or q in notes_blob:
                        data = result.get("data", {})
                        # Return first 8 key-value pairs as a snippet
                        snippet = dict(list(data.items())[:8])
                        matches.append({
                            "gauge_id": gid,
                            "slot": slot,
                            "snippet": snippet,
                        })
            except Exception:
                continue
        return matches

    def compare_gauges(
        self,
        gauge_ids: list[str] | None = None,
        slots: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Side-by-side comparison of metrics across gauges.

        Parameters
        ----------
        gauge_ids : list[str], optional
            Subset to compare. Defaults to all project gauges.
        slots : list[str], optional
            Which result slots to include. Defaults to signatures + model.
        """
        from ai_hydro.session.store import HydroSession
        target_gauges = gauge_ids or self.gauge_ids
        target_slots = slots or ["signatures", "geomorphic", "camels", "model"]
        comparison: dict[str, Any] = {}
        for gid in target_gauges:
            try:
                s = HydroSession.load(gid)
                row: dict[str, Any] = {}
                for slot in target_slots:
                    result = s.get(slot)
                    if result:
                        row[slot] = result.get("data", {})
                comparison[gid] = row
            except Exception:
                comparison[gid] = {"error": "could not load"}
        return comparison

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "gauge_ids": self.gauge_ids,
            "n_gauges": len(self.gauge_ids),
            "topics": self.topics,
            "literature_dir": self.literature_dir or str(self.literature_path),
            "n_journal_entries": len(self.journal),
            "n_notes": len(self.notes),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    # ------------------------------------------------------------------
    # research.md sync (project-aware)
    # ------------------------------------------------------------------

    def write_research_context(self) -> None:
        """
        Write a project-level digest to .clinerules/research.md.

        This file is auto-loaded into every AI-Hydro conversation, giving
        the agent immediate awareness of project state without any tool call.
        """
        lines: list[str] = [
            f"# Research Project: {self.name}",
            f"**Updated**: {self.updated_at[:10]}",
        ]

        if self.description:
            lines.append(f"**Description**: {self.description}")
        if self.topics:
            lines.append(f"**Topics**: {', '.join(self.topics)}")
        lines.append("")

        # Gauge overview
        if self.gauge_ids:
            lines.append(f"## Gauges ({len(self.gauge_ids)} associated)")
            from ai_hydro.session.store import HydroSession
            for gid in self.gauge_ids:
                try:
                    s = HydroSession.load(gid)
                    computed = s.computed()
                    label = f"  - **{gid}**: {', '.join(computed) if computed else 'no results yet'}"
                    # Add key metric if signatures available
                    if s.signatures:
                        bfi = s.signatures.get("data", {}).get("baseflow_index")
                        if bfi is not None:
                            label += f" (BFI={bfi:.2f})"
                    if s.model:
                        nse = s.model.get("data", {}).get("nse")
                        if nse is not None:
                            label += f" (NSE={nse:.3f})"
                    lines.append(label)
                except Exception:
                    lines.append(f"  - **{gid}**: could not load")
            lines.append("")

        # Recent journal entries
        if self.journal:
            lines.append(f"## Recent Journal ({len(self.journal)} total)")
            for entry in self.journal[-3:]:
                ts = entry.get("timestamp", "")[:10]
                text = entry.get("text", "")
                lines.append(f"  - [{ts}] {text}")
            lines.append("")

        # Notes
        if self.notes:
            lines.append("## Notes")
            for note in self.notes[-5:]:
                lines.append(f"  - {note}")
            lines.append("")

        # Literature
        lit_dir = Path(self.literature_dir) if self.literature_dir else self.literature_path
        if lit_dir.exists():
            docs = list(lit_dir.glob("*"))
            readable = [d for d in docs if d.suffix.lower() in (".pdf", ".txt", ".md")]
            if readable:
                lines.append(f"## Literature ({len(readable)} documents in {lit_dir})")
                if self.literature_index_path.exists():
                    lines.append("  - Index available: run `search_literature` to query papers.")
                else:
                    lines.append("  - Not yet indexed: run `index_literature` to build the index.")
                lines.append("")

        lines.append("> *Auto-generated by ProjectSession — do not edit manually.*")

        _RESEARCH_MD.parent.mkdir(parents=True, exist_ok=True)
        _RESEARCH_MD.write_text("\n".join(lines))
